SET @providerId = (SELECT ProviderId FROM ctm.provider_master WHERE providerCode='GOIN');

ALTER TABLE ctm.travel_product ALTER `productCode` DROP DEFAULT;
ALTER TABLE ctm.travel_product CHANGE COLUMN `productCode` `productCode` VARCHAR(64) NOT NULL AFTER `providerId`;

ALTER TABLE ctm.results_properties ALTER `productId` DROP DEFAULT;
ALTER TABLE ctm.results_properties CHANGE COLUMN `productId` `productId` VARCHAR(64) NOT NULL AFTER `transactionId`;


INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-base-region-1-excess-200', 'GO Insurance - Go Base', 'GO Insurance - Go Base', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-base-region-2-excess-200', 'GO Insurance - Go Base', 'GO Insurance - Go Base', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-base-region-3-excess-200', 'GO Insurance - Go Base', 'GO Insurance - Go Base', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-base-region-4-excess-200', 'GO Insurance - Go Base', 'GO Insurance - Go Base', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-base-region-1-excess-100', 'GO Insurance - Go Base', 'GO Insurance - Go Base', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-base-region-2-excess-100', 'GO Insurance - Go Base', 'GO Insurance - Go Base', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-base-region-3-excess-100', 'GO Insurance - Go Base', 'GO Insurance - Go Base', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-base-region-4-excess-100', 'GO Insurance - Go Base', 'GO Insurance - Go Base', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-basic-region-1-excess-200', 'GO Insurance - Go Basic', 'GO Insurance - Go Basic', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-basic-region-2-excess-200', 'GO Insurance - Go Basic', 'GO Insurance - Go Basic', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-basic-region-3-excess-200', 'GO Insurance - Go Basic', 'GO Insurance - Go Basic', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-basic-region-4-excess-200', 'GO Insurance - Go Basic', 'GO Insurance - Go Basic', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-basic-region-1-excess-100', 'GO Insurance - Go Basic', 'GO Insurance - Go Basic', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-basic-region-2-excess-100', 'GO Insurance - Go Basic', 'GO Insurance - Go Basic', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-basic-region-3-excess-100', 'GO Insurance - Go Basic', 'GO Insurance - Go Basic', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-basic-region-4-excess-100', 'GO Insurance - Go Basic', 'GO Insurance - Go Basic', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-plus-region-1-excess-200', 'GO Insurance - Go Plus', 'GO Insurance - Go Plus', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-plus-region-2-excess-200', 'GO Insurance - Go Plus', 'GO Insurance - Go Plus', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-plus-region-3-excess-200', 'GO Insurance - Go Plus', 'GO Insurance - Go Plus', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-plus-region-4-excess-200', 'GO Insurance - Go Plus', 'GO Insurance - Go Plus', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-plus-region-1-excess-100', 'GO Insurance - Go Plus', 'GO Insurance - Go Plus', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-plus-region-2-excess-100', 'GO Insurance - Go Plus', 'GO Insurance - Go Plus', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-plus-region-3-excess-100', 'GO Insurance - Go Plus', 'GO Insurance - Go Plus', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-st-go-plus-region-4-excess-100', 'GO Insurance - Go Plus', 'GO Insurance - Go Plus', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-31-go-basic-region-3-excess-200', 'Go Insurance AMT 31 Worldwide Excl North America, Canada and Antarctica - Go Basic (31 days)', 'Go Insurance AMT 31 Worldwide Excl North America, Canada and Antarctica - Go Basic (31 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-50-go-basic-region-3-excess-200', 'Go Insurance AMT 50 Worldwide Excl North America, Canada and Antarctica - Go Basic (50 days)', 'Go Insurance AMT 50 Worldwide Excl North America, Canada and Antarctica - Go Basic (50 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-60-go-basic-region-3-excess-200', 'Go Insurance AMT 60 Worldwide Excl North America, Canada and Antarctica - Go Basic (60 days)', 'Go Insurance AMT 60 Worldwide Excl North America, Canada and Antarctica - Go Basic (60 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-31-go-basic-region-4-excess-200', 'Go Insurance AMT 31 Worldwide - Go Basic (31 days)', 'Go Insurance AMT 31 Worldwide - Go Basic (31 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-60-go-basic-region-4-excess-200', 'Go Insurance AMT 50 Worldwide - Go Basic (50 days)', 'Go Insurance AMT 50 Worldwide - Go Basic (50 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-60-go-basic-region-4-excess-200', 'Go Insurance AMT 60 Worldwide - Go Basic (60 days)', 'Go Insurance AMT 60 Worldwide - Go Basic (60 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-31-go-basic-region-3-excess-100', 'Go Insurance AMT 31 Worldwide Excl North America, Canada and Antarctica - Go Basic (31 days)', 'Go Insurance AMT 31 Worldwide Excl North America, Canada and Antarctica - Go Basic (31 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-50-go-basic-region-3-excess-100', 'Go Insurance AMT 50 Worldwide Excl North America, Canada and Antarctica - Go Basic (50 days)', 'Go Insurance AMT 50 Worldwide Excl North America, Canada and Antarctica - Go Basic (50 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-60-go-basic-region-3-excess-100', 'Go Insurance AMT 60 Worldwide Excl North America, Canada and Antarctica - Go Basic (60 days)', 'Go Insurance AMT 60 Worldwide Excl North America, Canada and Antarctica - Go Basic (60 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-31-go-basic-region-4-excess-100', 'Go Insurance AMT 31 Worldwide - Go Basic (31 days)', 'Go Insurance AMT 31 Worldwide - Go Basic (31 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-60-go-basic-region-4-excess-100', 'Go Insurance AMT 50 Worldwide - Go Basic (50 days)', 'Go Insurance AMT 50 Worldwide - Go Basic (50 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-60-go-basic-region-4-excess-100', 'Go Insurance AMT 60 Worldwide - Go Basic (60 days)', 'Go Insurance AMT 60 Worldwide - Go Basic (60 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-31-go-plus-region-3-excess-200', 'Go Insurance AMT 31 Worldwide Excl North America, Canada and Antarctica - Go Plus (31 days)', 'Go Insurance AMT 31 Worldwide Excl North America, Canada and Antarctica - Go Plus (31 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');
INSERT INTO ctm.product_master (`ProductCat`, `providerId`, `productCode`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`) VALUES ('TRAVEL', @providerId, 'GOIN-TRAVEL-amt-31-go-plus-region-4-excess-200', 'Go Insurance AMT 31 Worldwide - Go Plus (31 days)', 'Go Insurance AMT 31 Worldwide - Go Plus (31 days)', '2015-09-20 00:00:00', '2040-12-31 00:00:00');


-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-S06', 324, 'Go Insurance - Go Plus', 'Go Insurance - Go Plus', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-S05', 324, 'Go Insurance - Go Plus', 'Go Insurance - Go Plus', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-S04', 324, 'Go Insurance - Go Basic', 'Go Insurance - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-S03', 324, 'Go Insurance - Go Basic', 'Go Insurance - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-S02', 324, 'Go Insurance - Go Base', 'Go Insurance - Go Base', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-S01', 324, 'Go Insurance - Go Base', 'Go Insurance - Go Base', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A12', 324, 'Go Insurance - AMT 100 60 days - Go Basic', 'Go Insurance AMT Worldwide (Excess 100) (60 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A11', 324, 'Go Insurance - AMT 100 50 days - Go Basic', 'Go Insurance AMT Worldwide (Excess 100) (50 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A10', 324, 'Go Insurance - AMT 100 31 days - Go Basic', 'Go Insurance AMT Worldwide (Excess 100) (31 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A09', 324, 'Go Insurance - AMT 200 60 days - Go Basic', 'Go Insurance AMT Worldwide (Excess 200) (60 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A08', 324, 'Go Insurance - AMT 200 50 days - Go Basic', 'Go Insurance AMT Worldwide (Excess 200) (50 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A07', 324, 'Go Insurance - AMT 200 31 days - Go Basic', 'Go Insurance AMT Worldwide (Excess 200) (31 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A06', 324, 'Go Insurance - AMT 100 60 days Excl - Go Basic', 'Go Insurance AMT Worldwide (Excess 100) Excl North America, Canada and Antarctica (60 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A05', 324, 'Go Insurance - AMT 100 50 days Excl - Go Basic', 'Go Insurance AMT Worldwide (Excess 100) Excl North America, Canada and Antarctica (50 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A04', 324, 'Go Insurance - AMT 100 31 days Excl - Go Basic', 'Go Insurance AMT Worldwide (Excess 100) Excl North America, Canada and Antarctica (31 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A03', 324, 'Go Insurance - AMT 200 60 days Excl - Go Basic', 'Go Insurance AMT Worldwide (Excess 200) Excl North America, Canada and Antarctica (60 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A02', 324, 'Go Insurance - AMT 200 50 days Excl - Go Basic', 'Go Insurance AMT Worldwide (Excess 200) Excl North America, Canada and Antarctica (50 days) - Go Basic', '2015-08-05', '2040-12-31', '');
-- INSERT INTO ctm.product_master (`ProductCat`, `productCode`, `providerId`, `ShortTitle`, `LongTitle`, `effectiveStart`, `effectiveEnd`, `Status`) VALUES ('TRAVEL', 'GOIN-TRAVEL-A01', 324, 'Go Insurance - AMT 200 31 days Excl - Go Basic', 'Go Insurance AMT Worldwide (Excess 200) Excl North America, Canada and Antarctica (31 days) - Go Basic', '2015-08-05', '2040-12-31', '');
