-- UPDATER 
SET @COMP = (SELECT carProductId FROM ctm.car_product WHERE code = 'REIN-01-02');
UPDATE ctm.car_product_content SET inclusions='<ul>  <li>24-month new for old car replacement cover if the car is a total loss</li>  <li>Cover for towing costs</li>  <li>Damage to trailer and caravan if attached to your car (belonging to you) ($1000)</li>  <li>Damage to personal property in your car ($500)</li>  <li>Child safety seats and prams replacement ($500)</li>  <li>Emergency travel and accommodation cover ($500)</li>  <li>Third party property damage cover for a substitute car</li>  <li>Locks and keys replacement ($1000)</li>  <li>Cover for your car while in transit</li>  <li>Essential repairs after the accident ($300)</li> </ul>', benefits='<ul>  <li>Option to take out Roadside Assistance cover.</li>  <li>Effortless claims – make a claim in minutes online 24 hours a day or over the phone.</li> </ul>', optionalExtras='<ul>  <li>Hire car cover</li>  <li>Excess-free windscreen cover</li> <li>Agreed value or market value – choose your own level of cover.</li>  </ul>' WHERE carProductId=@COMP;

-- CHECKER
SET @COMP = (SELECT carProductId FROM ctm.car_product WHERE code = 'REIN-01-02');
SELECT * FROM ctm.car_product_content WHERE carProductId IN (@COMP);

-- ROLLBACK
/*
SET @COMP = (SELECT carProductId FROM ctm.car_product WHERE code = 'REIN-01-02');
UPDATE ctm.car_product_content SET inclusions='<ul>  <li>12-month new for old car replacement cover if the car is a total loss</li>  <li>Cover for towing costs</li>  <li>Damage to trailer and caravan if attached to your car (belonging to you) ($1000)</li>  <li>Accidental damage to personal property ($500)</li>  <li>Child safety seats and prams replacement ($500)</li>  <li>Emergency transport and accommodation cover ($500 in total)</li>  <li>Third party property damage cover for a substitute car</li>  <li>Locks and keys replacement ($1000)</li>  <li>Cover for your car while in transit</li>  <li>Essential repairs after an accident or theft ($300)</li> </ul>', benefits='<ul>  <li>Option to take out Roadside Assistance cover.</li>  <li>Agreed value or market value – choose your own level of cover from a range of current values.</li>  <li>Effortless claims – make a claim in minutes online 24 hours a day or over the phone.</li> </ul>', optionalExtras='<ul>  <li>Pet cover ($1000)</li>  <li>Bicycle cover ($1000)</li>  <li>Hire car cover</li>  <li>Excess-free windscreen cover</li> </ul>' WHERE carProductId=@COMP;
*/