-- UPDATER
SET @PROV = (SELECT providerId FROM ctm.provider_master WHERE providerCode='TINZ');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-3-10',@PROV,'Single-WW Exc USA/Japan-Deluxe','Single-WW Exc USA/Japan-Deluxe','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-3-8',@PROV,'Single-WW Exc USA/Japan-Classic','Single-WW Exc USA/Japan-Classic','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-3-9',@PROV,'Single-WW Exc USA/Japan-Premier','Single-WW Exc USA/Japan-Premier','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-4-10',@PROV,'Single-WW Inc USA/Japan-Deluxe','Single-WW Inc USA/Japan-Deluxe','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-4-8',@PROV,'Single-WW Inc USA/Japan-Classic','Single-WW Inc USA/Japan-Classic','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-4-9',@PROV,'Single-WW Inc USA/Japan-Premier','Single-WW Inc USA/Japan-Premier','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-5-10',@PROV,'Single-Asia-Deluxe','Single-Asia-Deluxe','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-5-8',@PROV,'Single-Asia-Classic','Single-Asia-Classic','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-5-9',@PROV,'Single-Asia-Premier','Single-Asia-Premier','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-6-10',@PROV,'Single-South Pacific inc Bali & NZ-Deluxe','Single-South Pacific inc Bali & NZ-Deluxe','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-6-8',@PROV,'Single-South Pacific inc Bali & NZ-Classic','Single-South Pacific inc Bali & NZ-Classic','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-3-6-9',@PROV,'Single-South Pacific inc Bali & NZ-Premier','Single-South Pacific inc Bali & NZ-Premier','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-10-31',@PROV,'AMT-WW Exc USA/Japan-Deluxe-31Days','AMT-WW Exc USA/Japan-Deluxe-31Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-10-45',@PROV,'AMT-WW Exc USA/Japan-Deluxe-45Days','AMT-WW Exc USA/Japan-Deluxe-45Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-10-62',@PROV,'AMT-WW Exc USA/Japan-Deluxe-62Days','AMT-WW Exc USA/Japan-Deluxe-62Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-10-93',@PROV,'AMT-WW Exc USA/Japan-Deluxe-93Days','AMT-WW Exc USA/Japan-Deluxe-93Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-8-31',@PROV,'AMT-WW Exc USA/Japan-Classic-31Days','AMT-WW Exc USA/Japan-Classic-31Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-8-45',@PROV,'AMT-WW Exc USA/Japan-Classic-45Days','AMT-WW Exc USA/Japan-Classic-45Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-8-62',@PROV,'AMT-WW Exc USA/Japan-Classic-62Days','AMT-WW Exc USA/Japan-Classic-62Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-8-93',@PROV,'AMT-WW Exc USA/Japan-Classic-93Days','AMT-WW Exc USA/Japan-Classic-93Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-9-31',@PROV,'AMT-WW Exc USA/Japan-Premier-31Days','AMT-WW Exc USA/Japan-Premier-31Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-9-45',@PROV,'AMT-WW Exc USA/Japan-Premier-45Days','AMT-WW Exc USA/Japan-Premier-45Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-9-62',@PROV,'AMT-WW Exc USA/Japan-Premier-62Days','AMT-WW Exc USA/Japan-Premier-62Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-3-9-93',@PROV,'AMT-WW Inc USA/Japan-Deluxe-93Days','AMT-WW Inc USA/Japan-Deluxe-93Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-10-31',@PROV,'AMT-WW Inc USA/Japan-Deluxe-31Days','AMT-WW Inc USA/Japan-Deluxe-31Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-10-45',@PROV,'AMT-WW Inc USA/Japan-Deluxe-45Days','AMT-WW Inc USA/Japan-Deluxe-45Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-10-62',@PROV,'AMT-WW Inc USA/Japan-Deluxe-62Days','AMT-WW Inc USA/Japan-Deluxe-62Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-10-93',@PROV,'AMT-WW Inc USA/Japan-Deluxe-93Days','AMT-WW Inc USA/Japan-Deluxe-93Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-8-31',@PROV,'AMT-WW Inc USA/Japan-Classic-31Days','AMT-WW Inc USA/Japan-Classic-31Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-8-45',@PROV,'AMT-WW Inc USA/Japan-Classic-45Days','AMT-WW Inc USA/Japan-Classic-45Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-8-62',@PROV,'AMT-WW Inc USA/Japan-Classic-62Days','AMT-WW Inc USA/Japan-Classic-62Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-8-93',@PROV,'AMT-WW Inc USA/Japan-Classic-93Days','AMT-WW Inc USA/Japan-Classic-93Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-9-31',@PROV,'AMT-WW Inc USA/Japan-Premier-31Days','AMT-WW Inc USA/Japan-Premier-31Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-9-45',@PROV,'AMT-WW Inc USA/Japan-Premier-45Days','AMT-WW Inc USA/Japan-Premier-45Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-9-62',@PROV,'AMT-WW Inc USA/Japan-Premier-62Days','AMT-WW Inc USA/Japan-Premier-62Days','2015-08-18','2040-12-31','');
INSERT INTO ctm.product_master (productId,ProductCat,ProductCode,ProviderId,ShortTitle,LongTitle,EffectiveStart,EffectiveEnd,Status) VALUES (null,'TRAVEL','TINZ-TRAVEL-4-4-9-93',@PROV,'AMT-WW Inc USA/Japan-Premier-93Days','AMT-WW Inc USA/Japan-Premier-93Days','2015-08-18','2040-12-31','');


-- CHECKER - 36 products returned
SELECT * FROM ctm.product_master WHERE ProductCat='TRAVEL' AND ProductCode IN ('TINZ-TRAVEL-3-3-10','TINZ-TRAVEL-3-3-8','TINZ-TRAVEL-3-3-9','TINZ-TRAVEL-3-4-10','TINZ-TRAVEL-3-4-8','TINZ-TRAVEL-3-4-9','TINZ-TRAVEL-3-5-10','TINZ-TRAVEL-3-5-8','TINZ-TRAVEL-3-5-9','TINZ-TRAVEL-3-6-10','TINZ-TRAVEL-3-6-8','TINZ-TRAVEL-3-6-9','TINZ-TRAVEL-4-3-10-31','TINZ-TRAVEL-4-3-10-45','TINZ-TRAVEL-4-3-10-62','TINZ-TRAVEL-4-3-10-93','TINZ-TRAVEL-4-3-8-31','TINZ-TRAVEL-4-3-8-45','TINZ-TRAVEL-4-3-8-62','TINZ-TRAVEL-4-3-8-93','TINZ-TRAVEL-4-3-9-31','TINZ-TRAVEL-4-3-9-45','TINZ-TRAVEL-4-3-9-62','TINZ-TRAVEL-4-3-9-93','TINZ-TRAVEL-4-4-10-31','TINZ-TRAVEL-4-4-10-45','TINZ-TRAVEL-4-4-10-62','TINZ-TRAVEL-4-4-10-93','TINZ-TRAVEL-4-4-8-31','TINZ-TRAVEL-4-4-8-45','TINZ-TRAVEL-4-4-8-62','TINZ-TRAVEL-4-4-8-93','TINZ-TRAVEL-4-4-9-31','TINZ-TRAVEL-4-4-9-45','TINZ-TRAVEL-4-4-9-62','TINZ-TRAVEL-4-4-9-93');

-- ROLLBACK
/*
SET @PROV = (SELECT providerId FROM ctm.provider_master WHERE providerCode='TINZ');
DELETE FROM ctm.product_master WHERE ProductCat='TRAVEL' AND ProviderId=@PROV AND ProductCode IN ('TINZ-TRAVEL-3-3-10','TINZ-TRAVEL-3-3-8','TINZ-TRAVEL-3-3-9','TINZ-TRAVEL-3-4-10','TINZ-TRAVEL-3-4-8','TINZ-TRAVEL-3-4-9','TINZ-TRAVEL-3-5-10','TINZ-TRAVEL-3-5-8','TINZ-TRAVEL-3-5-9','TINZ-TRAVEL-3-6-10','TINZ-TRAVEL-3-6-8','TINZ-TRAVEL-3-6-9','TINZ-TRAVEL-4-3-10-31','TINZ-TRAVEL-4-3-10-45','TINZ-TRAVEL-4-3-10-62','TINZ-TRAVEL-4-3-10-93','TINZ-TRAVEL-4-3-8-31','TINZ-TRAVEL-4-3-8-45','TINZ-TRAVEL-4-3-8-62','TINZ-TRAVEL-4-3-8-93','TINZ-TRAVEL-4-3-9-31','TINZ-TRAVEL-4-3-9-45','TINZ-TRAVEL-4-3-9-62','TINZ-TRAVEL-4-3-9-93','TINZ-TRAVEL-4-4-10-31','TINZ-TRAVEL-4-4-10-45','TINZ-TRAVEL-4-4-10-62','TINZ-TRAVEL-4-4-10-93','TINZ-TRAVEL-4-4-8-31','TINZ-TRAVEL-4-4-8-45','TINZ-TRAVEL-4-4-8-62','TINZ-TRAVEL-4-4-8-93','TINZ-TRAVEL-4-4-9-31','TINZ-TRAVEL-4-4-9-45','TINZ-TRAVEL-4-4-9-62','TINZ-TRAVEL-4-4-9-93');
*/