/* New records for content type table
 * Including static html for all funds :
    1. About the fund
    2. Next step info
    3. Join declaration (Online)
    4. Join declaration (Call centre)
    */

INSERT INTO `ctm`.`provider_contents` (`providerContentTypeId`, `providerContentText`, `providerId`, `verticalId`, `effectiveStart`, `effectiveEnd`) VALUES
(1,'<p>Queensland Country Health Fund was established in 1977 as the MIM Employees Health Society. The Fund became an open health fund in 1999 enabling us to offer cover to a wider market, with a particular focus on regional and remote areas of Queensland.</p><p>We believe paying good benefits for health services is only part of providing great value. Our main focus is our Members and their family''s health. We''re committed to providing the best possible products and services within a simple and easy to understand product suite.</p><p>We offer some unique benefits for our Members, like the provision of unit accommodation in Townsville and Brisbane when required for essential medical reasons. This accommodation is offered exclusively to our Members at concessional rates. </p><p>We also have recently opened Queensland Country Dental at our new head office in Townsville. This provides our Members with access to high quality dental care with little or no out of pocket expenses (depending on level of Extras cover). The aim is to improve the oral health of our Members by making dental treatment more accessible and affordable.</p><p>We pride ourselves on our Member service! To ensure we maintain our high service standards, and to ensure our products continually meet our policy holder\'s needs, every year Queensland Country conduct a survey of its Members to ensure we keep in touch with what they really think. The good news is that from our last survey we were pleased to hear that 98% of respondents voiced that they were satisfied with us!</p><p>Queensland Country Health Fund policies operate on a unique, individualised membership year. The original establishment date of your policy represents the start date of this membership year. This start date is referred to as the anniversary date of your membership.</p>',16,4,'2015-01-01 00:00:01','2040-12-31 23:59:59'),
(2,'<ul><li>Your first premium payment will be deducted from your nominated bank account or credit card on receipt of your application by us, or from the actual start date of your policy. Subsequent premium payments will then be deducted in line with the selected payment frequency..</li><li>You will receive your Welcome Pack via your nominated contact method shortly. This pack contains important information about your Health Insurance policy, so please read all the information carefully. Your Membership Card should be received in the post within 10- 15 working days.</li><li>A representative of Queensland Country Health Fund will personally contact you soon to welcome you to our Fund, and to ensure that you fully understand all the details of your chosen cover.</li><li>Claims can only be processed, providing that all/any applicable waiting periods have been fully served and; if transferring from another Health Fund, providing that we are in receipt of your Clearance/Transfer Certificate from your previous Fund.</li></ul>',16,4,'2015-01-01 00:00:01','2040-12-31 23:59:59'),
(3,'<p>I authorise QCHF to debit my account and I agree to the <a href="http://www.qldcountryhealth.com.au/sites/default/files/images/hp_banners/Direct%20Debit%20Service%20Agreement.pdf" target="_blank">Direct Debit Service Agreement</a></p><p>I acknowledge that I have read the <a href="http://www.qldcountryhealth.com.au/sites/default/files/pdfs/Brochure_Privacy-Policy.pdf" target="_blank">Privacy Policy</a> and the <a href="http://www.qldcountryhealth.com.au/sites/default/files/pdfs/Brochure_Membership%20Guide.pdf" target="_blank">Membership Guide</a> in full and understand the terms and conditions of my cover, including those relating to pre-existing conditions, waiting periods, restricted benefit periods or any exclusions that apply to my cover. I declare that the information I have provided is true and correct. I acknowledge that, where practicable, information is provided with the consent of the individual to whom it relates.</p>',16,4,'2015-01-01 00:00:01','2040-12-31 23:59:59'),
(4,'<p>I authorise QCHF to debit my account and I agree to the <a href="http://www.qldcountryhealth.com.au/sites/default/files/images/hp_banners/Direct%20Debit%20Service%20Agreement.pdf" target="_blank">Direct Debit Service Agreement</a></p><p>I acknowledge that I have read the <a href="http://www.qldcountryhealth.com.au/sites/default/files/pdfs/Brochure_Privacy-Policy.pdf" target="_blank">Privacy Policy</a> and the <a href="http://www.qldcountryhealth.com.au/sites/default/files/pdfs/Brochure_Membership%20Guide.pdf" target="_blank">Membership Guide</a> in full and understand the terms and conditions of my cover, including those relating to pre-existing conditions, waiting periods, restricted benefit periods or any exclusions that apply to my cover. I declare that the information I have provided is true and correct. I acknowledge that, where practicable, information is provided with the consent of the individual to whom it relates.</p>',16,4,'2015-01-01 00:00:01','2040-12-31 23:59:59');
