-- UPDATER
SET @COMP = (SELECT carProductId FROM ctm.car_product WHERE code='AI-01-04');
SET @PLUS = (SELECT carProductId FROM ctm.car_product WHERE code='AI-01-05');
UPDATE ctm.car_product_content SET inclusions='<ul><li>12 months or 20,000km new for old car replacement cover</li><li>Finance gap cover up to a maximum of 20% of the MV</li><li>Tax audit cover up to a maximum of $5,000 </li></ul>', optionalExtras='<ul><li>Trade goods in transit cover up to a maximum of $3,000 per claim</li><li>Trade tools cover up to a maximum of $3,000 per claim</li><li>Trailer cover up to a maximum of $4,000 per claim</li><li>Hire Car cover (up to 14 days or up to $840)</li><li>Windscreen replacement (up to $1000)</li><li>Australia wide Roadside Assistance</li></ul>' WHERE carProductId=@COMP;
UPDATE ctm.car_product_content SET inclusions='<ul><li>12 months or 20,000km new for old car replacement cover</li><li>Finance gap cover up to a maximum of 20% of the MV</li><li>Tax audit cover up to a maximum of $5,000 </li></ul>', optionalExtras='<ul><li>Trade goods in transit cover up to a maximum of $3,000 per claim</li><li>Trade tools cover up to a maximum of $3,000 per claim</li><li>Trailer cover up to a maximum of $4,000 per claim</li><li>Hire Car cover (up to 14 days or up to $840)</li><li>Windscreen replacement (up to $1000)</li><li>Australia wide Roadside Assistance</li></ul>' WHERE carProductId=@PLUS;

-- CHECKER
SET @COMP = (SELECT carProductId FROM ctm.car_product WHERE code='AI-01-04');
SET @PLUS = (SELECT carProductId FROM ctm.car_product WHERE code='AI-01-05');
SELECT * FROM ctm.car_product_content WHERE carProductId IN (@COMP,@PLUS);

-- ROLLBACK
-- SET @COMP = (SELECT carProductId FROM ctm.car_product WHERE code='AI-01-04');
-- SET @PLUS = (SELECT carProductId FROM ctm.car_product WHERE code='AI-01-05');
-- UPDATE ctm.car_product_content SET inclusions='<ul><li>12 months or 20,000km new for old car replacement cover</li><li>Trade goods in transit cover up to a maximum of $5,000 per claim</li><li>Trade tools cover up to a maximum of $5,000 per claim</li><li>Trailer cover up to a maximum of $3,000 per claim</li><li>Finance gap cover up to a maximum of 20% of the MV</li><li>Tax audit cover up to a maximum of $5,000 </li></ul>', optionalExtras='<ul><li>Hire Car cover (up to 14 days or up to $840)</li><li>Windscreen replacement (up to $1000)</li><li>Australia wide Roadside Assistance</li></ul>' WHERE `group`='car' AND path='tech-content/car/ai-01-04/' AND cssSelector='#inclusions';
-- UPDATE ctm.car_product_content SET inclusions='<ul><li>12 months or 20,000km new for old car replacement cover</li><li>Trade goods in transit cover up to a maximum of $5,000 per claim</li><li>Trade tools cover up to a maximum of $5,000 per claim</li><li>Trailer cover up to a maximum of $3,000 per claim</li><li>Finance gap cover up to a maximum of 20% of the MV</li><li>Tax audit cover up to a maximum of $5,000 </li></ul>', optionalExtras='<ul><li>Hire Car cover (up to 14 days or up to $840)</li><li>Windscreen replacement (up to $1000)</li><li>Australia wide Roadside Assistance</li></ul>' WHERE `group`='car' AND path='tech-content/car/ai-01-05/' AND cssSelector='#inclusions';