INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Product name','feature',1,0,1,0,'productName','hncamsws_',0,1,'hidden-xs',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Product type','feature',1,0,2,0,'features.cvrType.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Home excess','feature',1,0,3,0,'homeExcess.amountFormatted','hncamsws_',0,0,'homeExcessFeature',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Contents excess','feature',1,0,4,0,'contentsExcess.amountFormatted','hncamsws_',0,0,'contentsExcessFeature',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Special Feature / Offer','category',1,0,5,0,'features.speFea.value','hncamsws_',0,1,'inverseRow hidden-xs',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('','feature',1,0,1,LAST_INSERT_ID(),'features.speFea.extra','hncamsws_',0,1,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Australian Call Centre','feature',1,0,6,0,'features.callcentre.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Temporary accommodation costs','feature',1,0,7,0,'features.tmpAccom.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Motor burnout option available','feature',1,0,8,0,'features.mtrBurn.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Fire or theft damage included','feature',1,0,9,0,'features.fireTheft.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Pet insurance available as a separate product','feature',1,0,10,0,'features.pets.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Protect contents left outside in the open','feature',1,0,11,0,'features.cntsOut.value','hncamsws_',0,0,'contentsFeature',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Accidental damage option available','feature',1,0,12,0,'features.accDam.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Protect contents away from the home','feature',1,0,13,0,'features.cntsAway.value','hncamsws_',0,0,'contentsFeature',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Credit card cover','category',1,0,14,0,'features.ccard.value','hncamsws_',0,0,'contentsFeature',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('','feature',1,0,1,LAST_INSERT_ID(),'features.ccard.extra','hncamsws_',0,1,'contentsFeature',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Uninsured guests'' contents cover','category',1,0,15,0,'features.guest.value','hncamsws_',0,0,'contentsFeature',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('','feature',1,0,1,LAST_INSERT_ID(),'features.guest.extra','hncamsws_',0,1,'contentsFeature',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Funeral expenses','category',1,0,16,0,'features.funeral.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('','feature',1,0,1,LAST_INSERT_ID(),'features.funeral.extra','hncamsws_',0,1,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Landlord insurance option available','feature',1,0,17,0,'features.landLord.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Flood cover option available','feature',1,0,18,0,'features.flood.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Storm and rainwater damage included','feature',1,0,19,0,'features.storm.value','hncamsws_',0,0,NULL,NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Lifetime building repair guarantee','feature',1,0,20,0,'features.lifeHome.value','hncamsws_',0,0,'homeFeature',NULL,0,NULL);
INSERT INTO `aggregator`.`features_details` (`name`,`type`,`status`,`categoryId`,`sequence`,`parentId`,`resultPath`,`vertical`,`expanded`,`multiRow`,`className`,`extraText`,`helpId`,`shortlistKey`) VALUES ('Lifetime contents repair guarantee','feature',1,0,21,0,'features.lifeCnts.value','hncamsws_',0,0,'contentsFeature',NULL,0,NULL);

-- Rollback
-- DELETE FROM `aggregator`.`features_details` WHERE vertical = 'hncamsws_';