START TRANSACTION;
/* UPDATES TO SCRAPE DATA FOR REAL AND WOOLWORTHS */

DELETE FROM ctm.scrapes where id in (95,96,97,98,99,100,101,102,103,104,105,106);
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (95,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#productName','<h2>Real Insurance</h2> <h3>Pay As You Drive Comprehensive Insurance</h3>','2013-03-08 16:55:05');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (96,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#inclusions','<h5>What&#39;s Included</h5> <ul>  <li>12-month new for old car replacement cover if the car is a total loss</li>  <li>Cover for towing costs</li>  <li>Damage to trailer and caravan if attached to your car (belonging to you) ($1000)</li>  <li>Accidental damage to personal property ($500)</li>  <li>Child safety seats and prams replacement ($500)</li>  <li>Emergency transport and accommodation cover ($500 in total)</li>  <li>Third party property damage cover for a substitute car</li>  <li>Locks and keys replacement ($1000)</li>  <li>Cover for your car while in transit</li>  <li>Essential repairs after an accident or theft ($300)</li> </ul>','2013-11-06 15:20:04');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (97,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#extras','<h5>Optional Extras</h5> <ul>  <li>Pet cover ($1000)</li>  <li>Bicycle cover ($1000)</li>  <li>Hire car cover</li>  <li>Excess-free windscreen cover</li> </ul>','2013-11-06 15:20:08');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (98,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#benefits','<h5>This insurance comes with some further features</h5> <ul>  <li>Option to take out Roadside Assistance cover.</li>  <li>Agreed value or market value – choose your own level of cover from a range of current values.</li>  <li>Effortless claims – make a claim in minutes online 24 hours a day or over the phone.</li> </ul>','2013-11-14 16:27:32');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (99,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#about','<h5>About the insurer</h5> <p>Real Insurance is part of the Hollard Group — one of the world&#39;s leading insurers. The Hollard Group now offers a broad range of life and general insurance products directly to retail customers as well as through specialised intermediaries. With offices in the United States, the United Kingdom, South Africa, Australia and throughout South East Asia and with over 6.5 million policies worldwide and over 1600 employees, you know you&#39;re in safe hands. </p>','2013-11-14 16:27:38');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (100,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#ad','',NULL);
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (101,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#productName','<h2>Real Insurance</h2> <h3>Comprehensive Car Insurance</h3>','2013-04-17 16:16:16');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (102,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#inclusions','<h5>What&#39;s Included</h5> <ul>  <li>12-month new for old car replacement cover if the car is a total loss</li>  <li>Cover for towing costs</li>  <li>Damage to trailer and caravan if attached to your car (belonging to you) ($1000)</li>  <li>Accidental damage to personal property ($500)</li>  <li>Child safety seats and prams replacement ($500)</li>  <li>Emergency transport and accommodation cover ($500 in total)</li>  <li>Third party property damage cover for a substitute car</li>  <li>Locks and keys replacement ($1000)</li>  <li>Cover for your car while in transit</li>  <li>Essential repairs after an accident or theft ($300)</li> </ul>','2013-11-06 15:20:27');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (103,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#extras','<h5>Optional Extras</h5> <ul>  <li>Pet cover ($1000)</li>  <li>Bicycle cover ($1000)</li>  <li>Hire car cover</li>  <li>Excess-free windscreen cover</li> </ul>','2013-11-06 15:20:32');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (104,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#benefits','<h5>This insurance comes with some further features</h5> <ul>  <li>Option to take out Roadside Assistance cover.</li>  <li>Agreed value or market value – choose your own level of cover from a range of current values.</li>  <li>Effortless claims – make a claim in minutes online 24 hours a day or over the phone.</li> </ul>','2013-11-14 16:28:03');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (105,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#about','<h5>About the insurer</h5> <p>Real Insurance is part of the Hollard Group — one of the world&#39;s leading insurers. The Hollard Group now offers a broad range of life and general insurance products directly to retail customers as well as through specialised intermediaries. With offices in the United States, the United Kingdom, South Africa, Australia and throughout South East Asia and with over 6.5 million policies worldwide and over 1600 employees, you know you&#39;re in safe hands.</p>','2013-11-06 15:20:39');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (106,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#ad','',NULL);

DELETE FROM ctm.scrapes where id in (115,116,117,118,119,120,121,122,123,124,125,126);
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (115,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-01/','#productName','<h2>Woolworths Insurance</h2> <h3>Drive Less Pay Less Comprehensive Insurance</h3>','2013-10-29 15:44:18');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (116,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-01/','#inclusions','<h5>What&#39;s Included</h5> <ul>  <li>12-month new for old car replacement cover if the car is a total loss</li>  <li>Cover for towing costs</li>  <li>Damage to trailer and caravan if attached to your car (belonging to you) ($1000)</li>  <li>Accidental damage to personal property ($500)</li>  <li>Child safety seats and prams replacement ($500)</li>  <li>Emergency transport and accommodation cover ($500 in total)</li>  <li>Third party property damage cover for a substitute car</li>  <li>Locks and keys replacement ($1000)</li>  <li>Cover for your car while in transit</li>  <li>Essential repairs after an accident or theft ($300)</li> </ul>','2013-11-06 10:37:17');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (117,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-01/','#extras','<h5>Optional Extras</h5> <ul>  <li>Roadside Assistance cover</li>  <li>Hire car cover</li>  <li>Excess-free windscreen cover</li> </ul>','2013-11-14 16:26:22');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (118,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-01/','#benefits','<h5>This insurance comes with some further features</h5> <ul>  <li>Agreed value or market value – choose your own level of cover from a range of current values</li>  <li>Pay monthly at no extra cost</li>  <li>24 hour emergency claims assistance helpline</li> </ul>','2013-11-14 16:26:26');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (119,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-01/','#about','<h5>About the insurer</h5> <p>Woolworths Insurance has been providing customers with a range of car, travel and pet insurance products since 2011. Woolworths Car Insurance offers various types of cover including Comprehensive, and Make Your Own that allows customers to tailor their car insurance for their needs and budget. Woolworths partners with The Hollard Insurance Company Pty Ltd, a leading international insurance provider to provide its Car Insurance product.  Woolworths Ltd ABN 88 000 014 675 AR No. 245476 (Woolworths) acts as Hollard&#39;s authorised representative.</p>','2013-11-05 14:12:54');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (120,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-01/','#ad','',NULL);
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (121,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-02/','#productName','<h2>Woolworths Insurance</h2> <h3>Woolworths Comprehensive Insurance</h3>','2013-10-29 15:43:30');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (122,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-02/','#inclusions','<h5>What&#39;s Included</h5> <ul>  <li>12-month new for old car replacement cover if the car is a total loss</li>  <li>Cover for towing costs</li>  <li>Damage to trailer and caravan if attached to your car (belonging to you) ($1000)</li>  <li>Accidental damage to personal property ($500)</li>  <li>Child safety seats and prams replacement ($500)</li>  <li>Emergency transport and accommodation cover ($500 in total)</li>  <li>Third party property damage cover for a substitute car</li>  <li>Locks and keys replacement ($1000)</li>  <li>Cover for your car while in transit</li>  <li>Essential repairs after an accident or theft ($300)</li> </ul>','2013-11-06 10:37:44');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (123,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-02/','#extras','<h5>Optional Extras</h5> <ul>  <li>Roadside Assistance cover</li>  <li>Hire car cover</li>  <li>Excess-free windscreen cover</li> </ul>','2013-11-14 16:26:48');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (124,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-02/','#benefits','<h5>This insurance comes with some further features</h5> <ul>  <li>Agreed value or market value – choose your own level of cover from a range of current values</li>  <li>Pay monthly at no extra cost</li>  <li>24 hour emergency claims assistance helpline</li> </ul>','2013-11-14 16:26:53');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (125,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-02/','#about','<h5>About the insurer</h5> <p>Woolworths Insurance has been providing customers with a range of car, travel and pet insurance products since 2011. Woolworths Car Insurance offers various types of cover including Comprehensive, and Make Your Own that allows customers to tailor their car insurance for their needs and budget. Woolworths partners with The Hollard Insurance Company Pty Ltd, a leading international insurance provider to provide its Car Insurance product.  Woolworths Ltd ABN 88 000 014 675 AR No. 245476 (Woolworths) acts as Hollard&#39;s authorised representative.</p>','2013-11-05 14:13:15');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (126,'car','http://www.comparethemarket.com.au','tech-content/car/wool-01-02/','#ad','',NULL);

-- ROLLBACK;
-- COMMIT;