UPDATE `aggregator`.`features_details` SET `className`='CTMNoIcon-assistedreproduction' WHERE `id`='6960';
UPDATE `aggregator`.`features_details` SET `className`='CTMNoIcon-majoreyesurgery' WHERE `id`='6963';
UPDATE `aggregator`.`features_details` SET `className`='CTMNoIcon-privatehospital' WHERE `id`='6952';
UPDATE `aggregator`.`features_details` SET `className`='CTMNoIcon-gastric' WHERE `id`='6975';
UPDATE `aggregator`.`features_details` SET `className`='CTMNoIcon-palliative' WHERE `id`='6981';
UPDATE `aggregator`.`features_details` SET `className`='CTMNoIcon-cosmeticsurgery' WHERE `id`='6969';
UPDATE `aggregator`.`features_details` SET `className`='CTMNoIcon-rehabilitation' WHERE `id`='6987';
UPDATE `aggregator`.`features_details` SET `className`='CTMNoIcon-dialysis' WHERE `id`='6978';
UPDATE `aggregator`.`features_details` SET `className`='CTMNoIcon-sterilisation' WHERE `id`='6972';