-- TEST
SELECT * FROM ctm.scrapes
WHERE id IN( 95,96,97,98,99,100,101,102,103,104,105,106 );

/*
-- Query: select * from ctm.scrapes where id in (95,96,97,98,99,100,101,102,103,104,105,106)
LIMIT 0, 1000

-- Date: 2013-11-06 15:42
*/
DELETE FROM ctm.scrapes
WHERE id IN( 95,96,97,98,99,100,101,102,103,104,105,106 );

INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (95,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#productName','<h2>Real Insurance</h2> <h3>Pay As You Drive Comprehensive Insurance</h3>','2013-03-08 16:55:05');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (96,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#inclusions','<h5>What&#39;s Included</h5> <ul>  <li>12-month new for old car replacement cover if the car is a total loss</li>  <li>Cover for towing costs</li>  <li>Damage to trailer and caravan if attached to your car (belonging to you) ($1000)</li>  <li>Accidental damage to personal property ($500)</li>  <li>Child safety seats and prams replacement ($500)</li>  <li>Emergency transport and accommodation cover ($500 in total)</li>  <li>Third party property damage cover for a substitute car</li>  <li>Locks and keys replacement ($1000)</li>  <li>Cover for your car while in transit</li>  <li>Essential repairs after an accident or theft ($300)</li> </ul>','2013-11-06 15:20:04');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (97,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#extras','<h5>Optional Extras</h5> <ul>  <li>Pet cover ($1000)</li>  <li>Bicycle cover ($1000)</li>  <li>Hire car cover</li>  <li>Excess-free windscreen cover</li> </ul>','2013-11-06 15:20:08');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (98,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#benefits','<h5>This insurance comes with some further features</h5> <ul>  <li>Option to take out roadside assistance cover.</li>  <li>Agreed value or market value – choose your own level of cover from a range of current values.</li>  <li>Effortless claims – make a claim in minutes online 24 hours a day or over the phone.</li> </ul>','2013-11-06 15:20:12');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (99,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#about','<h5>About the insurer</h5> <p>Real Insurance is part of the Hollard Group — one of the world&#39;s leading insurers. The Hollard Group now offers a broad range of life and general insurance products directly to retail customers as well as through specialised intermediaries. With offices in the United States, the United Kingdom, South Africa, Australia and throughout South East Asia and with over 6.5 million policies worldwide and over 1600 employees, you know you&#39;re in safe hands.</p>','2013-11-06 15:20:15');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (100,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-01/','#ad','',NULL);
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (101,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#productName','<h2>Real Insurance</h2> <h3>Comprehensive Car Insurance</h3>','2013-04-17 16:16:16');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (102,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#inclusions','<h5>What&#39;s Included</h5> <ul>  <li>12-month new for old car replacement cover if the car is a total loss</li>  <li>Cover for towing costs</li>  <li>Damage to trailer and caravan if attached to your car (belonging to you) ($1000)</li>  <li>Accidental damage to personal property ($500)</li>  <li>Child safety seats and prams replacement ($500)</li>  <li>Emergency transport and accommodation cover ($500 in total)</li>  <li>Third party property damage cover for a substitute car</li>  <li>Locks and keys replacement ($1000)</li>  <li>Cover for your car while in transit</li>  <li>Essential repairs after an accident or theft ($300)</li> </ul>','2013-11-06 15:20:27');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (103,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#extras','<h5>Optional Extras</h5> <ul>  <li>Pet cover ($1000)</li>  <li>Bicycle cover ($1000)</li>  <li>Hire car cover</li>  <li>Excess-free windscreen cover</li> </ul>','2013-11-06 15:20:32');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (104,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#benefits','<h5>This insurance comes with some further features</h5> <ul>  <li>Option to take out roadside assistance cover.</li>  <li>Agreed value or market value – choose your own level of cover from a range of current values.</li>  <li>Effortless claims – make a claim in minutes online 24 hours a day or over the phone.</li> </ul>','2013-11-06 15:20:36');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (105,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#about','<h5>About the insurer</h5> <p>Real Insurance is part of the Hollard Group — one of the world&#39;s leading insurers. The Hollard Group now offers a broad range of life and general insurance products directly to retail customers as well as through specialised intermediaries. With offices in the United States, the United Kingdom, South Africa, Australia and throughout South East Asia and with over 6.5 million policies worldwide and over 1600 employees, you know you&#39;re in safe hands.</p>','2013-11-06 15:20:39');
INSERT INTO ctm.scrapes (`id`,`group`,`url`,`path`,`cssSelector`,`html`,`last_updated`) VALUES (106,'car','http://www.comparethemarket.com.au','tech-content/car/rein-01-02/','#ad','',NULL);
