<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="/WEB-INF/tags/taglib.tagf" %>

<jsp:useBean id="data" class="com.disc_au.web.go.Data" scope="session" />

<core:doctype />
<go:html>
	<core:head title="GMHBA Connection Test" />
	<body>
		<c:set var="testXML">
<health>
	<application>
		<dependants>
			<dependant3>
				<school></school>
				<title>MR</title>
				<dob>01/01/1991</dob>
				<firstName>Pluto</firstName>
				<lastname>Dog</lastname>
			</dependant3>
			<dependant6>
				<title></title>
				<dob></dob>
				<lastname></lastname>
				<school></school>
				<firstName></firstName>
			</dependant6>
			<dependant4>
				<title></title>
				<firstName></firstName>
				<school></school>
				<lastname></lastname>
				<dob></dob>
			</dependant4>
			<dependant10>
				<dob></dob>
				<school></school>
				<firstName></firstName>
				<title></title>
				<lastname></lastname>
			</dependant10>
			<dependant8>
				<firstName></firstName>
				<school></school>
				<title></title>
				<dob></dob>
				<lastname></lastname>
			</dependant8>
			<dependant5>
				<lastname></lastname>
				<title></title>
				<dob></dob>
				<school></school>
				<firstName></firstName>
			</dependant5>
			<dependant2>
				<firstName>Mickey</firstName>
				<lastname>Mouse</lastname>
				<school>School2</school>
				<title>MR</title>
				<dob>01/01/1989</dob>
			</dependant2>
			<dependant12>
				<school></school>
				<title></title>
				<lastname></lastname>
				<dob></dob>
				<firstName></firstName>
			</dependant12>
			<dependant11>
				<title></title>
				<school></school>
				<firstName></firstName>
				<lastname></lastname>
				<dob></dob>
			</dependant11>
			<dependant9>
				<title></title>
				<lastname></lastname>
				<school></school>
				<dob></dob>
				<firstName></firstName>
			</dependant9>
			<dependant1>
				<lastname>Mouse</lastname>
				<firstName>Minnie</firstName>
				<title>MISS</title>
				<school>School1</school>
				<dob>01/01/1988</dob>
			</dependant1>
			<dependant7>
				<dob></dob>
				<lastname></lastname>
				<title></title>
				<firstName></firstName>
				<school></school>
			</dependant7>
			<income></income>
		</dependants>
		<postal>
			<streetSearch></streetSearch>
			<state></state>
			<sbrSeq></sbrSeq>
			<postCode></postCode>
			<unitSel></unitSel>
			<unitShop></unitShop>
			<nonStdStreet></nonStdStreet>
			<suburbName></suburbName>
			<suburb></suburb>
			<streetNum></streetNum>
			<lastSearch></lastSearch>
			<houseNoSel></houseNoSel>
			<streetName></streetName>
			<type>P</type>
			<streetId></streetId>
		</postal>
		<address>
			<nonStd>Y</nonStd>
			<streetName>sherwood</streetName>
			<type>R</type>
			<lastSearch></lastSearch>
			<sbrSeq></sbrSeq>
			<postCode>4066</postCode>
			<unitSel></unitSel>
			<state>QLD</state>
			<houseNoSel></houseNoSel>
			<streetNum>9</streetNum>
			<suburbName>Toowong</suburbName>
			<suburb>7984</suburb>
			<streetId></streetId>
			<nonStdStreet>sherwood</nonStdStreet>
			<unitShop></unitShop>
			<streetSearch></streetSearch>
		</address>
		<product>PHIO-HEALTH-12034</product>
		<primary>
			<dob>01/01/1961</dob>
			<surname>Person</surname>
			<title>MR</title>
			<gender>M</gender>
			<firstname>Test</firstname>
		</primary>
		<partner>
			<gender>F</gender>
			<firstname>Test</firstname>
			<dob>01/01/1961</dob>
			<title>MRS</title>
			<surname>Partner</surname>
		</partner>
		<mobile>0712341234</mobile>
		<other></other>
		<provider>HCF</provider>
		<postalMatch>Y</postalMatch>
		<email>test@person.com</email>
	</application>
	<benefits>
		<benefitsExtras>
			<Optical>Y</Optical>
			<DentalGeneral>Y</DentalGeneral>
			<PrHospital>Y</PrHospital>
		</benefitsExtras>
		<healthSitu>YC</healthSitu>
	</benefits>
	<payment>
		<bank>
			<account></account>
			<name></name>
			<day></day>
			<number></number>
			<bsb></bsb>
		</bank>
		<medicare>
			<middleInitial>I</middleInitial>
			<firstName>MediFirst</firstName>
			<expiry>
				<cardExpiryMonth>09</cardExpiryMonth>
				<cardExpiryYear>13</cardExpiryYear>
			</expiry>
			<surname>MediLast</surname>
			<cover>Y</cover>
			<number>4297098813</number>
		</medicare>
		<credit>
			<number>4000000000000002</number>
			<expiry>
				<cardExpiryYear>15</cardExpiryYear>
				<cardExpiryMonth>04</cardExpiryMonth>
			</expiry>
			<type>v</type>
			<day>10</day>
			<name>CCName</name>
			<ccv>012</ccv>
		</credit>
		<details>
			<start>19/11/2012</start>
			<frequency>M</frequency>
			<type>cc</type>
		</details>
	</payment>
	<contactDetails>
		<call>Y</call>
		<email>test@person.com</email>
		<firstName>Test</firstName>
		<lastname>Person</lastname>
		<contactNumber>
			<other>0712341234</other>
			<mobile>0712341234</mobile>
		</contactNumber>

	</contactDetails>
	<declaration>Y</declaration>
	<healthCover>
		<partner>
			<cover>Y</cover>
			<healthCoverLoading>Y</healthCoverLoading>
			<dob>01/01/1961</dob>
		</partner>
		<primary>
			<healthCoverLoading>Y</healthCoverLoading>
			<cover>Y</cover>
			<dob>01/01/1961</dob>
		</primary>
		<dependants>3</dependants>
		<rebate>Y</rebate>
		<income>2</income>
	</healthCover>
	<show-price>M</show-price>
	<excess>4</excess>
	<previousfund>
		<partner>
			<memberID>678910</memberID>
			<fundName>FRANK</fundName>
		</partner>
		<primary>
			<memberID>012345</memberID>
			<fundName>AHM</fundName>
		</primary>
	</previousfund>
	<situation>
		<state>QLD</state>
		<healthSitu>YC</healthSitu>
		<healthCvr>F</healthCvr>
	</situation>
	<rank-by>B</rank-by>
	<loading>0</loading>
	<rebate>10</rebate>
	<clientIpAddress>0:0:0:0:0:0:0:1</clientIpAddress>
	<transactionId>17525</transactionId>
</health>
		</c:set>

		<c:import var="config" url="/WEB-INF/aggregator/health_application/gmhba/config.xml" />
		<go:soapAggregator config = "${config}"
						transactionId = "1234"
						xml = "${testXML}"
						var = "resultXml"
						debugVar="debugXml" />

	</body>
</go:html>