SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-P');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/261182836;116033926;d;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-F');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/261182835;116033653;z;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-LR');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/261182833;116030897;e;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-LRP');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/264606485;116032947;j;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-R');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/261182831;116033729;z;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-RP');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/263376941;116030343;x;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-RB');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/282862299;116034616;l;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-FF');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/261182834;116033937;d;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-FFP');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/261182832;116033843;x;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
SET @productId = (SELECT productId FROM ctm.product_master WHERE productcode ='ANZ-FFB');
UPDATE ctm.product_properties SET text = 'https://ad.doubleclick.net/ddm/clk/282869129;116032645;k;' WHERE productId = @productId AND propertyId='handover-url' LIMIT 1;
