SET @CAR_VERTICAL_ID = (SELECT verticalId FROM ctm.vertical_master WHERE verticalCode = 'TRAVEL');
SET @SERVICE_MASTER_ID = (SELECT serviceMasterId FROM ctm.service_master WHERE verticalId=@CAR_VERTICAL_ID AND serviceCode='quoteServiceBER');

SET @PROVIDER_ID = (SELECT ProviderId FROM ctm.provider_master WHERE providerCode='STIN' AND status<>'X');

UPDATE ctm.service_properties SET servicePropertyValue = 'https://uat.simplytravelinsurance.com.au' WHERE serviceMasterId = @SERVICE_MASTER_ID
AND environmentCode = '0' AND providerId = @PROVIDER_ID AND servicePropertyKey = 'url';

UPDATE ctm.service_properties SET servicePropertyValue = 'https://www.simplytravelinsurance.com.au' WHERE serviceMasterId = @SERVICE_MASTER_ID
AND environmentCode = 'PRO' AND providerId = @PROVIDER_ID AND servicePropertyKey = 'url';

UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=1FOW,trackCode=37' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = '1FOW');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=BUDD,trackCode=36' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'BUDD');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=VIRG,quoteUrl=https://uat-aspire.agaassistance.com.au/virginmoney/,trackCode=21' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'VIRG');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=VIRG,quoteUrl=https://travel.virginmoney.com.au/,trackCode=21' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'VIRG');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=OTIS,quoteUrl=https://uat-oti.agaassistance.com.au,trackCode=34' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'OTIS');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=OTIS,quoteUrl=https://www.onlinetravelinsurance.com.au,trackCode=34' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'OTIS');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=AMEX,rootURL=https://amex.acetravelinsurance.com/AU,trackCode=39' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'AMEX');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=AMEX,rootURL=https://amex.atuat.acegroup.com/AUResp/,trackCode=39' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'AMEX');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=CLBS,agentCode=COZ,quoteUrl=https://travel.columbusdirect.com.au/landingService.cfm,trackCode=7' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'CLBS');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=FAST,trackCode=14' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'FAST');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=DUIN,trackCode=8' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'DUIN');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=1COV,trackCode=61' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = '1COV');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=SKII,trackCode=64' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'SKII');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=30UN,trackCode=63' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = '30UN');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=INGO,trackCode=22' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'INGO');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=TINZ,trackCode=23' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'TINZ');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=KANG,trackCode=62' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'KANG');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ITRK,trackCode=65' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ITRK');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=WEBJ,quoteUrl=https://uat-webjetau.agaassistance.com.au,trackCode=52' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'WEBJ');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=WEBJ,quoteUrl=https://www.webjet.com.au/insurance,trackCode=52' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'WEBJ');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ZUJI,quoteUrl=https://uat-zuji.agaassistance.com.au,trackCode=35' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ZUJI');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ZUJI,quoteUrl=https://www.zuji.com.au/insurance,trackCode=35' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ZUJI');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=PPTI,rootURL=https://www.pricelineprotects.com.au/Quote,trackCode=60' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'PPTI');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=PPTI,rootURL=https://www.pricelineprotects.com.au/Quote,trackCode=60' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'PPTI');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ACET,rootURL=https://citibank.aceinsurance.com.au/Travel-Insurance/Quote-,trackCode=28' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ACET');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ACET,rootURL=https://citibank.aceinsurance.com.au/Travel-Insurance/Quote-,trackCode=28' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ACET');
UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=TICK,trackCode=66' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'TICK');

UPDATE ctm.service_properties SET servicePropertyValue = 'clientCode=VMON' WHERE environmentCode = '0' AND servicePropertyKey = 'outboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'VIRG');
UPDATE ctm.service_properties SET servicePropertyValue = 'clientCode=OTIAU' WHERE environmentCode = '0' AND servicePropertyKey = 'outboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'OTIS');
UPDATE ctm.service_properties SET servicePropertyValue = 'clientCode=WEBJETAU' WHERE environmentCode = '0' AND servicePropertyKey = 'outboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'WEBJ');
UPDATE ctm.service_properties SET servicePropertyValue = 'clientCode=ZUJIAU' WHERE environmentCode = '0' AND servicePropertyKey = 'outboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ZUJI');

SET @PROVIDER_ID = (SELECT ProviderId FROM ctm.provider_master WHERE providerCode='STIN' AND status<>'X');
INSERT INTO ctm.service_properties (serviceMasterId, providerId, environmentCode, styleCodeId, servicePropertyKey, servicePropertyValue, effectiveStart, effectiveEnd, scope) VALUES
  (@SERVICE_MASTER_ID, @PROVIDER_ID, '0',0,'inboundParams','quoteUrl=http://uat.simplytravelinsurance.com.au','2014-01-01 00:00:00', '2038-01-19 00:00:00', 'SERVICE'),
  (@SERVICE_MASTER_ID, @PROVIDER_ID, 'PRO',0,'inboundParams','quoteUrl=http://www.simplytravelinsurance.com.au','2014-01-01 00:00:00', '2038-01-19 00:00:00', 'SERVICE');

SET @PROVIDER_ID = (SELECT ProviderId FROM ctm.provider_master WHERE providerCode='SCTI' AND status<>'X');
INSERT INTO ctm.service_properties (serviceMasterId, providerId, environmentCode, styleCodeId, servicePropertyKey, servicePropertyValue, effectiveStart, effectiveEnd, scope) VALUES
  (@SERVICE_MASTER_ID, @PROVIDER_ID, '0',0,'inboundParams','quoteUrl=http://pp1.scti.com.au/979230','2014-01-01 00:00:00', '2038-01-19 00:00:00', 'SERVICE'),
  (@SERVICE_MASTER_ID, @PROVIDER_ID, 'NXI',0,'inboundParams','quoteUrl=http://pp2.scti.com.au/quote','2014-01-01 00:00:00', '2038-01-19 00:00:00', 'SERVICE'),
  (@SERVICE_MASTER_ID, @PROVIDER_ID, 'NXS',0,'inboundParams','quoteUrl=http://pp2.scti.com.au/quote','2014-01-01 00:00:00', '2038-01-19 00:00:00', 'SERVICE'),
  (@SERVICE_MASTER_ID, @PROVIDER_ID, 'NXQ',0,'inboundParams','quoteUrl=http://pp2.scti.com.au/quote','2014-01-01 00:00:00', '2038-01-19 00:00:00', 'SERVICE'),
  (@SERVICE_MASTER_ID, @PROVIDER_ID, 'PRO',0,'inboundParams','quoteUrl=http://www.scti.com.au/quote','2014-01-01 00:00:00', '2038-01-19 00:00:00', 'SERVICE');


-- Rollback
-- SET @CAR_VERTICAL_ID = (SELECT verticalId FROM ctm.vertical_master WHERE verticalCode = 'TRAVEL');
-- SET @SERVICE_MASTER_ID = (SELECT serviceMasterId FROM ctm.service_master WHERE verticalId=@CAR_VERTICAL_ID AND serviceCode='quoteServiceBER');
--
-- SET @PROVIDER_ID = (SELECT ProviderId FROM ctm.provider_master WHERE providerCode='STIN' AND status<>'X');
--
-- UPDATE ctm.service_properties SET servicePropertyValue = 'uat.simplytravelinsurance.com.au' WHERE serviceMasterId = @SERVICE_MASTER_ID
-- AND environmentCode = '0' AND providerId = @PROVIDER_ID AND servicePropertyKey = 'url';
--
-- UPDATE ctm.service_properties SET servicePropertyValue = 'www.simplytravelinsurance.com.au' WHERE serviceMasterId = @SERVICE_MASTER_ID
-- AND environmentCode = 'PRO' AND providerId = @PROVIDER_ID AND servicePropertyKey = 'url';
--
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=1FOW' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = '1FOW');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=BUDD' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'BUDD');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=VIRG,quoteUrl=https://uat-aspire.agaassistance.com.au/virginmoney/' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'VIRG');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=VIRG,quoteUrl=https://travel.virginmoney.com.au/' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'VIRG');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=OTIS,quoteUrl=https://uat-oti.agaassistance.com.au' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'OTIS');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=OTIS,quoteUrl=https://www.onlinetravelinsurance.com.au' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'OTIS');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=AMEX,rootURL=https://amex.acetravelinsurance.com/AU' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'AMEX');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=AMEX,rootURL=https://amex.atuat.acegroup.com/AUResp/' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'AMEX');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=CLBS,agentCode=COZ,quoteUrl=https://travel.columbusdirect.com.au/landingService.cfm' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'CLBS');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=FAST' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'FAST');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=DUIN' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'DUIN');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=1COV' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = '1COV');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=SKII' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'SKII');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=30UN' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = '30UN');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=INGO' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'INGO');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=TINZ' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'TINZ');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=KANG' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'KANG');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ITRK' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ITRK');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=WEBJ,quoteUrl=https://uat-webjetau.agaassistance.com.au' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'WEBJ');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=WEBJ,quoteUrl=https://www.webjet.com.au/insurance' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'WEBJ');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ZUJI,quoteUrl=https://uat-zuji.agaassistance.com.au' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ZUJI');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ZUJI,quoteUrl=https://www.zuji.com.au/insurance' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ZUJI');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=PPTI,rootURL=https://www.pricelineprotects.com.au/Quote' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'PPTI');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=PPTI,rootURL=https://www.pricelineprotects.com.au/Quote' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'PPTI');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ACET,rootURL=https://citibank.aceinsurance.com.au/Travel-Insurance/Quote-' WHERE environmentCode = 'PRO' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ACET');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=ACET,rootURL=https://citibank.aceinsurance.com.au/Travel-Insurance/Quote-' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ACET');
-- UPDATE ctm.service_properties SET servicePropertyValue = 'defaultProductId=NODEFAULT,service=TICK' WHERE environmentCode = '0' AND servicePropertyKey = 'inboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'TICK');
--
-- UPDATE ctm.service_properties SET servicePropertyValue = '' WHERE environmentCode = '0' AND servicePropertyKey = 'outboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'VIRG');
-- UPDATE ctm.service_properties SET servicePropertyValue = '' WHERE environmentCode = '0' AND servicePropertyKey = 'outboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'OTIS');
-- UPDATE ctm.service_properties SET servicePropertyValue = '' WHERE environmentCode = '0' AND servicePropertyKey = 'outboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'WEBJ');
-- UPDATE ctm.service_properties SET servicePropertyValue = '' WHERE environmentCode = '0' AND servicePropertyKey = 'outboundParams'  AND serviceMasterId = @SERVICE_MASTER_ID AND providerId = (SELECT providerId FROM ctm.provider_master WHERE providerCode = 'ZUJI');
--
-- SET @PROVIDER_ID = (SELECT ProviderId FROM ctm.provider_master WHERE providerCode='STIN' AND status<>'X');
-- DELETE ctm.service_properties WHERE serviceMasterId = @SERVICE_MASTER_ID AND providerId = @PROVIDER_ID AND servicePopertyKey = 'inboundParams';
--
-- SET @PROVIDER_ID = (SELECT ProviderId FROM ctm.provider_master WHERE providerCode='SCTI' AND status<>'X');
-- DELETE ctm.service_properties WHERE serviceMasterId = @SERVICE_MASTER_ID AND providerId = @PROVIDER_ID AND servicePopertyKey = 'inboundParams';