insert into ref_tbGoodNamesList(Name) values('ANALIESE');
insert into ref_tbGoodNamesList(Name) values('Thanaluxsumi');
insert into ref_tbGoodNamesList(Name) values('"ZIANAL F A"');
insert into ref_tbGoodNamesList(Name) values('Anusha');
insert into ref_tbGoodNamesList(Name) values('Anusheel');
insert into ref_tbGoodNamesList(Name) values('ANUSHIA');
insert into ref_tbGoodNamesList(Name) values('Anushka');
insert into ref_tbGoodNamesList(Name) values('Anushree');
insert into ref_tbGoodNamesList(Name) values('Haubianus');
insert into ref_tbGoodNamesList(Name) values('"Hermanus Jacobus Haasbroek"');
insert into ref_tbGoodNamesList(Name) values('MANUS');
insert into ref_tbGoodNamesList(Name) values('Manush');
insert into ref_tbGoodNamesList(Name) values('"MARY ANUSHKA"');
insert into ref_tbGoodNamesList(Name) values('STEPHANUS');
insert into ref_tbGoodNamesList(Name) values('"Yvonne Januschka"');
insert into ref_tbGoodNamesList(Name) values('ARIAN');
insert into ref_tbGoodNamesList(Name) values('ARIANA');
insert into ref_tbGoodNamesList(Name) values('Ariane');
insert into ref_tbGoodNamesList(Name) values('Arianna');
insert into ref_tbGoodNamesList(Name) values('ARIANNE');
insert into ref_tbGoodNamesList(Name) values('CARIANNE');
insert into ref_tbGoodNamesList(Name) values('Darian');
insert into ref_tbGoodNamesList(Name) values('Karianne');
insert into ref_tbGoodNamesList(Name) values('MARIAN');
insert into ref_tbGoodNamesList(Name) values('"Marian Phyllis"');
insert into ref_tbGoodNamesList(Name) values('Mariana');
insert into ref_tbGoodNamesList(Name) values('Marianna');
insert into ref_tbGoodNamesList(Name) values('Marianne');
insert into ref_tbGoodNamesList(Name) values('"Marianne Yanni"');
insert into ref_tbGoodNamesList(Name) values('Mariano');
insert into ref_tbGoodNamesList(Name) values('Larseric');
insert into ref_tbGoodNamesList(Name) values('Pearse');
insert into ref_tbGoodNamesList(Name) values('ARYAN');
insert into ref_tbGoodNamesList(Name) values('Maryana');
insert into ref_tbGoodNamesList(Name) values('MARYANN');
insert into ref_tbGoodNamesList(Name) values('"Maryann Kutia"');
insert into ref_tbGoodNamesList(Name) values('MARYANNA');
insert into ref_tbGoodNamesList(Name) values('MARYANNE');
insert into ref_tbGoodNamesList(Name) values('Alhassan');
insert into ref_tbGoodNamesList(Name) values('Anastassios');
insert into ref_tbGoodNamesList(Name) values('Assunta');
insert into ref_tbGoodNamesList(Name) values('BASSAM');
insert into ref_tbGoodNamesList(Name) values('bassem');
insert into ref_tbGoodNamesList(Name) values('Cass');
insert into ref_tbGoodNamesList(Name) values('CASSA');
insert into ref_tbGoodNamesList(Name) values('Cassandra');
insert into ref_tbGoodNamesList(Name) values('Cassaundra');
insert into ref_tbGoodNamesList(Name) values('CASSEY');
insert into ref_tbGoodNamesList(Name) values('CASSIDY');
insert into ref_tbGoodNamesList(Name) values('Cassie');
insert into ref_tbGoodNamesList(Name) values('Cassie-Anne');
insert into ref_tbGoodNamesList(Name) values('Cassinta');
insert into ref_tbGoodNamesList(Name) values('Cassius');
insert into ref_tbGoodNamesList(Name) values('Cassy');
insert into ref_tbGoodNamesList(Name) values('"Charity Cassandra Monique"');
insert into ref_tbGoodNamesList(Name) values('Douglass');
insert into ref_tbGoodNamesList(Name) values('"Farah Hassan"');
insert into ref_tbGoodNamesList(Name) values('GHASSAN');
insert into ref_tbGoodNamesList(Name) values('HADASSAH');
insert into ref_tbGoodNamesList(Name) values('Hassaan');
insert into ref_tbGoodNamesList(Name) values('HASSAN');
insert into ref_tbGoodNamesList(Name) values('Hassanul');
insert into ref_tbGoodNamesList(Name) values('Inass');
insert into ref_tbGoodNamesList(Name) values('Jesudass');
insert into ref_tbGoodNamesList(Name) values('"Jill Bassett"');
insert into ref_tbGoodNamesList(Name) values('kassan');
insert into ref_tbGoodNamesList(Name) values('Kassandra');
insert into ref_tbGoodNamesList(Name) values('kassey');
insert into ref_tbGoodNamesList(Name) values('Kassie');
insert into ref_tbGoodNamesList(Name) values('KRASSIMIRA');
insert into ref_tbGoodNamesList(Name) values('"Margaret Glass"');
insert into ref_tbGoodNamesList(Name) values('"Mario Basso"');
insert into ref_tbGoodNamesList(Name) values('MASSIMILIANO');
insert into ref_tbGoodNamesList(Name) values('Massimo');
insert into ref_tbGoodNamesList(Name) values('Masson');
insert into ref_tbGoodNamesList(Name) values('"Megan Passman"');
insert into ref_tbGoodNamesList(Name) values('Nass');
insert into ref_tbGoodNamesList(Name) values('Nassar');
insert into ref_tbGoodNamesList(Name) values('Nasser');
insert into ref_tbGoodNamesList(Name) values('Nassrin');
insert into ref_tbGoodNamesList(Name) values('"Natassa Costi"');
insert into ref_tbGoodNamesList(Name) values('"Richard Michael Brassil"');
insert into ref_tbGoodNamesList(Name) values('"Samantha Douglass"');
insert into ref_tbGoodNamesList(Name) values('Sassica');
insert into ref_tbGoodNamesList(Name) values('"Steven Bass"');
insert into ref_tbGoodNamesList(Name) values('"Steven Glass"');
insert into ref_tbGoodNamesList(Name) values('Thomass');
insert into ref_tbGoodNamesList(Name) values('Tomasso');
insert into ref_tbGoodNamesList(Name) values('Vassiliki');
insert into ref_tbGoodNamesList(Name) values('Vassos');
insert into ref_tbGoodNamesList(Name) values('Wassail');
insert into ref_tbGoodNamesList(Name) values('WASSAN');
insert into ref_tbGoodNamesList(Name) values('WASSIM');
insert into ref_tbGoodNamesList(Name) values('Yasser');
insert into ref_tbGoodNamesList(Name) values('Jazz');
insert into ref_tbGoodNamesList(Name) values('Nazzarena');
insert into ref_tbGoodNamesList(Name) values('Nazzareno');
insert into ref_tbGoodNamesList(Name) values('"Shale Mazza"');
insert into ref_tbGoodNamesList(Name) values('SHAZZA');
insert into ref_tbGoodNamesList(Name) values('Franses');
insert into ref_tbGoodNamesList(Name) values('FRANSISCUS');
insert into ref_tbGoodNamesList(Name) values('"Jessica Susan"');
insert into ref_tbGoodNamesList(Name) values('BABER');
insert into ref_tbGoodNamesList(Name) values('Bambang');
insert into ref_tbGoodNamesList(Name) values('"Eugene Banganay"');
insert into ref_tbGoodNamesList(Name) values('ABEER');
insert into ref_tbGoodNamesList(Name) values('Harbeer');
insert into ref_tbGoodNamesList(Name) values('Bodene');
insert into ref_tbGoodNamesList(Name) values('BODIE');
insert into ref_tbGoodNamesList(Name) values('Prabodhan');
insert into ref_tbGoodNamesList(Name) values('Slobodan');
insert into ref_tbGoodNamesList(Name) values('SLOBODANKA');
insert into ref_tbGoodNamesList(Name) values('EBONEE');
insert into ref_tbGoodNamesList(Name) values('Abra');
insert into ref_tbGoodNamesList(Name) values('ABRAHAM');
insert into ref_tbGoodNamesList(Name) values('Ambra-maria');
insert into ref_tbGoodNamesList(Name) values('Barabra');
insert into ref_tbGoodNamesList(Name) values('Barbra');
insert into ref_tbGoodNamesList(Name) values('Brad');
insert into ref_tbGoodNamesList(Name) values('"Brad Cole"');
insert into ref_tbGoodNamesList(Name) values('"Brad Colton"');
insert into ref_tbGoodNamesList(Name) values('"Brad Hogg"');
insert into ref_tbGoodNamesList(Name) values('"Brad Ross"');
insert into ref_tbGoodNamesList(Name) values('"Brad Smith"');
insert into ref_tbGoodNamesList(Name) values('BRADD');
insert into ref_tbGoodNamesList(Name) values('BRADEN');
insert into ref_tbGoodNamesList(Name) values('Bradford');
insert into ref_tbGoodNamesList(Name) values('bradie');
insert into ref_tbGoodNamesList(Name) values('Bradlee');
insert into ref_tbGoodNamesList(Name) values('Bradley');
insert into ref_tbGoodNamesList(Name) values('"Bradley  Wilson"');
insert into ref_tbGoodNamesList(Name) values('"Bradley Cochrane"');
insert into ref_tbGoodNamesList(Name) values('"Bradley Culph"');
insert into ref_tbGoodNamesList(Name) values('"Bradley De San"');
insert into ref_tbGoodNamesList(Name) values('"Bradley Deutscher"');
insert into ref_tbGoodNamesList(Name) values('"Bradley John"');
insert into ref_tbGoodNamesList(Name) values('"Bradley Jolly"');
insert into ref_tbGoodNamesList(Name) values('"Bradley Livingstone-Fog"');
insert into ref_tbGoodNamesList(Name) values('"Bradley S"');
insert into ref_tbGoodNamesList(Name) values('"Bradley Simmons"');
insert into ref_tbGoodNamesList(Name) values('"Bradley Talbot"');
insert into ref_tbGoodNamesList(Name) values('"Bradley Williams"');
insert into ref_tbGoodNamesList(Name) values('Bradly');
insert into ref_tbGoodNamesList(Name) values('bradney');
insert into ref_tbGoodNamesList(Name) values('Brady');
insert into ref_tbGoodNamesList(Name) values('Brae');
insert into ref_tbGoodNamesList(Name) values('Braeden');
insert into ref_tbGoodNamesList(Name) values('Braeton');
insert into ref_tbGoodNamesList(Name) values('braid');
insert into ref_tbGoodNamesList(Name) values('Bramerdharshani');
insert into ref_tbGoodNamesList(Name) values('BRAMWELL');
insert into ref_tbGoodNamesList(Name) values('Bran');
insert into ref_tbGoodNamesList(Name) values('Branden');
insert into ref_tbGoodNamesList(Name) values('Brandon');
insert into ref_tbGoodNamesList(Name) values('"Brandon Brunner"');
insert into ref_tbGoodNamesList(Name) values('"Brandon McCamley"');
insert into ref_tbGoodNamesList(Name) values('"Brandon Preuss"');
insert into ref_tbGoodNamesList(Name) values('Brandt');
insert into ref_tbGoodNamesList(Name) values('BRANISLAV');
insert into ref_tbGoodNamesList(Name) values('"Branislav Panajic"');
insert into ref_tbGoodNamesList(Name) values('Branka');
insert into ref_tbGoodNamesList(Name) values('BRANKICA');
insert into ref_tbGoodNamesList(Name) values('Branko');
insert into ref_tbGoodNamesList(Name) values('BRATISLAV');
insert into ref_tbGoodNamesList(Name) values('"Braxton Neate"');
insert into ref_tbGoodNamesList(Name) values('BRAYDEN');
insert into ref_tbGoodNamesList(Name) values('Brayden-Lee');
insert into ref_tbGoodNamesList(Name) values('BRAYDIN');
insert into ref_tbGoodNamesList(Name) values('Braydon');
insert into ref_tbGoodNamesList(Name) values('Debabrata');
insert into ref_tbGoodNamesList(Name) values('Debbra');
insert into ref_tbGoodNamesList(Name) values('Debra');
insert into ref_tbGoodNamesList(Name) values('Debrah');
insert into ref_tbGoodNamesList(Name) values('Dubravka');
insert into ref_tbGoodNamesList(Name) values('Ebrahim');
insert into ref_tbGoodNamesList(Name) values('"Gavin Brady"');
insert into ref_tbGoodNamesList(Name) values('Gebrael');
insert into ref_tbGoodNamesList(Name) values('GIBRAN');
insert into ref_tbGoodNamesList(Name) values('ibrahim');
insert into ref_tbGoodNamesList(Name) values('"John Abraham"');
insert into ref_tbGoodNamesList(Name) values('"John Brawn"');
insert into ref_tbGoodNamesList(Name) values('"Lauren Brandley"');
insert into ref_tbGoodNamesList(Name) values('Librawan');
insert into ref_tbGoodNamesList(Name) values('"Luke Brandley"');
insert into ref_tbGoodNamesList(Name) values('"Matthew Abraham"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Bray"');
insert into ref_tbGoodNamesList(Name) values('Obrad');
insert into ref_tbGoodNamesList(Name) values('"Osborne Braganza"');
insert into ref_tbGoodNamesList(Name) values('"Peter Brandon"');
insert into ref_tbGoodNamesList(Name) values('REMBRANDT');
insert into ref_tbGoodNamesList(Name) values('"Tracey Brand"');
insert into ref_tbGoodNamesList(Name) values('"Troy Bradley Thorpe"');
insert into ref_tbGoodNamesList(Name) values('"Ralph Buttigieg"');
insert into ref_tbGoodNamesList(Name) values('"Bernadette Hancock"');
insert into ref_tbGoodNamesList(Name) values('Cocks');
insert into ref_tbGoodNamesList(Name) values('"Craig Hiscock"');
insert into ref_tbGoodNamesList(Name) values('"Jaro Cockman"');
insert into ref_tbGoodNamesList(Name) values('"Jolene Hiscock"');
insert into ref_tbGoodNamesList(Name) values('"Trudy Jeacock"');
insert into ref_tbGoodNamesList(Name) values('"Damien Cox"');
insert into ref_tbGoodNamesList(Name) values('"Terry Cox"');
insert into ref_tbGoodNamesList(Name) values('Cumhur');
insert into ref_tbGoodNamesList(Name) values('Dagoberto');
insert into ref_tbGoodNamesList(Name) values('Dick');
insert into ref_tbGoodNamesList(Name) values('Dickon');
insert into ref_tbGoodNamesList(Name) values('"James Cobbledick"');
insert into ref_tbGoodNamesList(Name) values('"Dinkar Premji"');
insert into ref_tbGoodNamesList(Name) values('Dinko');
insert into ref_tbGoodNamesList(Name) values('"Bun Dong"');
insert into ref_tbGoodNamesList(Name) values('Dong');
insert into ref_tbGoodNamesList(Name) values('"DONG HEE"');
insert into ref_tbGoodNamesList(Name) values('"Dong Nguyen"');
insert into ref_tbGoodNamesList(Name) values('"DONG SEOK"');
insert into ref_tbGoodNamesList(Name) values('"DONG SUN"');
insert into ref_tbGoodNamesList(Name) values('DONGHAI');
insert into ref_tbGoodNamesList(Name) values('DONGHENG');
insert into ref_tbGoodNamesList(Name) values('DONGHO');
insert into ref_tbGoodNamesList(Name) values('DONGHWAN');
insert into ref_tbGoodNamesList(Name) values('donghyuk');
insert into ref_tbGoodNamesList(Name) values('DONGSHUN');
insert into ref_tbGoodNamesList(Name) values('Dongup');
insert into ref_tbGoodNamesList(Name) values('Dongyeop');
insert into ref_tbGoodNamesList(Name) values('"WEI DONG"');
insert into ref_tbGoodNamesList(Name) values('WEIDONG');
insert into ref_tbGoodNamesList(Name) values('Wendong');
insert into ref_tbGoodNamesList(Name) values('"XIAO DONG"');
insert into ref_tbGoodNamesList(Name) values('XIAODONG');
insert into ref_tbGoodNamesList(Name) values('xidong');
insert into ref_tbGoodNamesList(Name) values('FANNY');
insert into ref_tbGoodNamesList(Name) values('fatema');
insert into ref_tbGoodNamesList(Name) values('Faten');
insert into ref_tbGoodNamesList(Name) values('"Fathima Raban"');
insert into ref_tbGoodNamesList(Name) values('FATIH');
insert into ref_tbGoodNamesList(Name) values('FATIMA');
insert into ref_tbGoodNamesList(Name) values('"FATIMA PATRICIA"');
insert into ref_tbGoodNamesList(Name) values('Fatimah');
insert into ref_tbGoodNamesList(Name) values('FATMA');
insert into ref_tbGoodNamesList(Name) values('"FATMA DENIZ"');
insert into ref_tbGoodNamesList(Name) values('Fatme');
insert into ref_tbGoodNamesList(Name) values('"Hung Fat"');
insert into ref_tbGoodNamesList(Name) values('"Selefuti Pula-Fatu"');
insert into ref_tbGoodNamesList(Name) values('"FOOK HAN"');
insert into ref_tbGoodNamesList(Name) values('"Kok Fook"');
insert into ref_tbGoodNamesList(Name) values('"Ching fuk Anson"');
insert into ref_tbGoodNamesList(Name) values('"FUK PING"');
insert into ref_tbGoodNamesList(Name) values('GAE-SOOK');
insert into ref_tbGoodNamesList(Name) values('GAEL');
insert into ref_tbGoodNamesList(Name) values('Gaelle');
insert into ref_tbGoodNamesList(Name) values('Gaenor');
insert into ref_tbGoodNamesList(Name) values('GAETANO');
insert into ref_tbGoodNamesList(Name) values('"Abbygail Cintamani"');
insert into ref_tbGoodNamesList(Name) values('ABIGAIL');
insert into ref_tbGoodNamesList(Name) values('GAI');
insert into ref_tbGoodNamesList(Name) values('Gai-Maree');
insert into ref_tbGoodNamesList(Name) values('GAIBRIELLE');
insert into ref_tbGoodNamesList(Name) values('Gail');
insert into ref_tbGoodNamesList(Name) values('"GAIL M"');
insert into ref_tbGoodNamesList(Name) values('Gailene');
insert into ref_tbGoodNamesList(Name) values('"Jacqueline Gail"');
insert into ref_tbGoodNamesList(Name) values('Lauagaia');
insert into ref_tbGoodNamesList(Name) values('"MARY ABIGAIL"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Gai"');
insert into ref_tbGoodNamesList(Name) values('Mingai');
insert into ref_tbGoodNamesList(Name) values('"Moogambigai Amudhabalan"');
insert into ref_tbGoodNamesList(Name) values('Ngaire');
insert into ref_tbGoodNamesList(Name) values('Ngairi');
insert into ref_tbGoodNamesList(Name) values('NIANGAI');
insert into ref_tbGoodNamesList(Name) values('Nygaire');
insert into ref_tbGoodNamesList(Name) values('"Paul Gaiardo"');
insert into ref_tbGoodNamesList(Name) values('Tsungai');
insert into ref_tbGoodNamesList(Name) values('"Charles Gaylard"');
insert into ref_tbGoodNamesList(Name) values('Gay');
insert into ref_tbGoodNamesList(Name) values('Gaya');
insert into ref_tbGoodNamesList(Name) values('"Gayan Thushara Pierisge Fernando"');
insert into ref_tbGoodNamesList(Name) values('Gayantha');
insert into ref_tbGoodNamesList(Name) values('GAYDOU');
insert into ref_tbGoodNamesList(Name) values('Gaye');
insert into ref_tbGoodNamesList(Name) values('Gayl');
insert into ref_tbGoodNamesList(Name) values('Gayle');
insert into ref_tbGoodNamesList(Name) values('GAYLEEN');
insert into ref_tbGoodNamesList(Name) values('Gaylene');
insert into ref_tbGoodNamesList(Name) values('Gaylyn');
insert into ref_tbGoodNamesList(Name) values('GAYNOR');
insert into ref_tbGoodNamesList(Name) values('"LYNETTE GAY"');
insert into ref_tbGoodNamesList(Name) values('TURGAY');
insert into ref_tbGoodNamesList(Name) values('Sergey');
insert into ref_tbGoodNamesList(Name) values('"Amanda Goddard"');
insert into ref_tbGoodNamesList(Name) values('GODFREY');
insert into ref_tbGoodNamesList(Name) values('Godwin');
insert into ref_tbGoodNamesList(Name) values('"Margaret Goddard"');
insert into ref_tbGoodNamesList(Name) values('"Mark Godresse"');
insert into ref_tbGoodNamesList(Name) values('"Matthew Goddard"');
insert into ref_tbGoodNamesList(Name) values('guido');
insert into ref_tbGoodNamesList(Name) values('Hebert');
insert into ref_tbGoodNamesList(Name) values('Phebe');
insert into ref_tbGoodNamesList(Name) values('Sheeba');
insert into ref_tbGoodNamesList(Name) values('ANNE-MICHELLE');
insert into ref_tbGoodNamesList(Name) values('"Barrie Bushell"');
insert into ref_tbGoodNamesList(Name) values('BURCHELL');
insert into ref_tbGoodNamesList(Name) values('chellese');
insert into ref_tbGoodNamesList(Name) values('Chelline');
insert into ref_tbGoodNamesList(Name) values('Hellen');
insert into ref_tbGoodNamesList(Name) values('"Jeremiah Hellmuth"');
insert into ref_tbGoodNamesList(Name) values('Leachelle');
insert into ref_tbGoodNamesList(Name) values('"Leone Michelle"');
insert into ref_tbGoodNamesList(Name) values('Marie-Michelle');
insert into ref_tbGoodNamesList(Name) values('MECHELLE');
insert into ref_tbGoodNamesList(Name) values('micehelle');
insert into ref_tbGoodNamesList(Name) values('Michell');
insert into ref_tbGoodNamesList(Name) values('Michelle');
insert into ref_tbGoodNamesList(Name) values('"Michelle Alfrey"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Denise"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Gregory"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Hewison"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Leonard"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Lotz"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Mackay"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Meyer"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Norton"');
insert into ref_tbGoodNamesList(Name) values('"MICHELLE PUNITA"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Sheather"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Spooner"');
insert into ref_tbGoodNamesList(Name) values('"Michelle Van Rensburg"');
insert into ref_tbGoodNamesList(Name) values('MICHELLIE');
insert into ref_tbGoodNamesList(Name) values('Michellle');
insert into ref_tbGoodNamesList(Name) values('"Misan Michell"');
insert into ref_tbGoodNamesList(Name) values('Mischelle');
insert into ref_tbGoodNamesList(Name) values('Mitchell');
insert into ref_tbGoodNamesList(Name) values('"Mitchell Gerrans"');
insert into ref_tbGoodNamesList(Name) values('"Mitchell Kekwick"');
insert into ref_tbGoodNamesList(Name) values('Mychelle');
insert into ref_tbGoodNamesList(Name) values('Rachell');
insert into ref_tbGoodNamesList(Name) values('Rachelle');
insert into ref_tbGoodNamesList(Name) values('RAICHELLE');
insert into ref_tbGoodNamesList(Name) values('RAYCHELL');
insert into ref_tbGoodNamesList(Name) values('Raychelle');
insert into ref_tbGoodNamesList(Name) values('rechelle');
insert into ref_tbGoodNamesList(Name) values('RICHELLE');
insert into ref_tbGoodNamesList(Name) values('"Richelle Anne"');
insert into ref_tbGoodNamesList(Name) values('rochelle');
insert into ref_tbGoodNamesList(Name) values('"Rochelle McKnight"');
insert into ref_tbGoodNamesList(Name) values('Shellaine');
insert into ref_tbGoodNamesList(Name) values('Shelle');
insert into ref_tbGoodNamesList(Name) values('Shelle-Ann');
insert into ref_tbGoodNamesList(Name) values('SHELLEE');
insert into ref_tbGoodNamesList(Name) values('SHELLENA');
insert into ref_tbGoodNamesList(Name) values('Shelley');
insert into ref_tbGoodNamesList(Name) values('Shelley-Anne');
insert into ref_tbGoodNamesList(Name) values('Shelli-Ann');
insert into ref_tbGoodNamesList(Name) values('SHELLIE');
insert into ref_tbGoodNamesList(Name) values('Shellie-Ann');
insert into ref_tbGoodNamesList(Name) values('Shelly');
insert into ref_tbGoodNamesList(Name) values('Dhivya');
insert into ref_tbGoodNamesList(Name) values('Prithiviraj');
insert into ref_tbGoodNamesList(Name) values('Shiva');
insert into ref_tbGoodNamesList(Name) values('"SHIVA RAJ"');
insert into ref_tbGoodNamesList(Name) values('Shivam');
insert into ref_tbGoodNamesList(Name) values('Shivana');
insert into ref_tbGoodNamesList(Name) values('SHIVANI');
insert into ref_tbGoodNamesList(Name) values('"Shivani Maharaj"');
insert into ref_tbGoodNamesList(Name) values('SHIVANTHAN');
insert into ref_tbGoodNamesList(Name) values('SHIVON');
insert into ref_tbGoodNamesList(Name) values('"Todd Hoare"');
insert into ref_tbGoodNamesList(Name) values('ASHOOR');
insert into ref_tbGoodNamesList(Name) values('"Deva Shore"');
insert into ref_tbGoodNamesList(Name) values('Kishore');
insert into ref_tbGoodNamesList(Name) values('"KISHORE REDDY"');
insert into ref_tbGoodNamesList(Name) values('nandakishore');
insert into ref_tbGoodNamesList(Name) values('Shorena');
insert into ref_tbGoodNamesList(Name) values('Thoreen');
insert into ref_tbGoodNamesList(Name) values('HUMPHREY');
insert into ref_tbGoodNamesList(Name) values('"John Humphrey"');
insert into ref_tbGoodNamesList(Name) values('Japneesh');
insert into ref_tbGoodNamesList(Name) values('Jerko');
insert into ref_tbGoodNamesList(Name) values('"Fiona Winskill"');
insert into ref_tbGoodNamesList(Name) values('KILLIAN');
insert into ref_tbGoodNamesList(Name) values('kkk');
insert into ref_tbGoodNamesList(Name) values('"Bali Strickland"');
insert into ref_tbGoodNamesList(Name) values('"David Blokland"');
insert into ref_tbGoodNamesList(Name) values('kirkland');
insert into ref_tbGoodNamesList(Name) values('"Robert Buckland"');
insert into ref_tbGoodNamesList(Name) values('"Colette Kock"');
insert into ref_tbGoodNamesList(Name) values('AMITKUMAR');
insert into ref_tbGoodNamesList(Name) values('"Arun Kumar"');
insert into ref_tbGoodNamesList(Name) values('Arunkumar');
insert into ref_tbGoodNamesList(Name) values('Avanishkumar');
insert into ref_tbGoodNamesList(Name) values('"Benay Kumar"');
insert into ref_tbGoodNamesList(Name) values('Bhabinkumar');
insert into ref_tbGoodNamesList(Name) values('Birenkumar');
insert into ref_tbGoodNamesList(Name) values('CHETANKUMAR');
insert into ref_tbGoodNamesList(Name) values('Chintankumar');
insert into ref_tbGoodNamesList(Name) values('Chiragkumar');
insert into ref_tbGoodNamesList(Name) values('"Chiragkumar Joshi"');
insert into ref_tbGoodNamesList(Name) values('Darshankumar');
insert into ref_tbGoodNamesList(Name) values('Deokumar');
insert into ref_tbGoodNamesList(Name) values('Devendrakumar');
insert into ref_tbGoodNamesList(Name) values('DHAVALKUMAR');
insert into ref_tbGoodNamesList(Name) values('"Dinesh Kumar"');
insert into ref_tbGoodNamesList(Name) values('"Ganesh Kumar"');
insert into ref_tbGoodNamesList(Name) values('"HARISH KUMAR"');
insert into ref_tbGoodNamesList(Name) values('HIRENDRAKUMAR');
insert into ref_tbGoodNamesList(Name) values('INDRAKUMAR');
insert into ref_tbGoodNamesList(Name) values('Jayeshkumar');
insert into ref_tbGoodNamesList(Name) values('Kalpeshkumar');
insert into ref_tbGoodNamesList(Name) values('KETUKUMAR');
insert into ref_tbGoodNamesList(Name) values('Kirtikumar');
insert into ref_tbGoodNamesList(Name) values('KUMAR');
insert into ref_tbGoodNamesList(Name) values('"Kumar Saimon"');
insert into ref_tbGoodNamesList(Name) values('KUMARASINGHE');
insert into ref_tbGoodNamesList(Name) values('KUMARAVELLAN');
insert into ref_tbGoodNamesList(Name) values('KUMARVEL');
insert into ref_tbGoodNamesList(Name) values('Kumi');
insert into ref_tbGoodNamesList(Name) values('Kumiko');
insert into ref_tbGoodNamesList(Name) values('Kumuditha');
insert into ref_tbGoodNamesList(Name) values('KUMUTHA');
insert into ref_tbGoodNamesList(Name) values('"MANOJ KUMAR"');
insert into ref_tbGoodNamesList(Name) values('"MAYUR KUMAR"');
insert into ref_tbGoodNamesList(Name) values('Mehulkumar');
insert into ref_tbGoodNamesList(Name) values('Mittalkumar');
insert into ref_tbGoodNamesList(Name) values('Muthukumar');
insert into ref_tbGoodNamesList(Name) values('NAIMESHKUMAR');
insert into ref_tbGoodNamesList(Name) values('NANDAKUMAR');
insert into ref_tbGoodNamesList(Name) values('NARENDRAKUMAR');
insert into ref_tbGoodNamesList(Name) values('"Naresh Kumar"');
insert into ref_tbGoodNamesList(Name) values('Nimeshkumar');
insert into ref_tbGoodNamesList(Name) values('"Nirav Kumar N"');
insert into ref_tbGoodNamesList(Name) values('NIRAVKUMAR');
insert into ref_tbGoodNamesList(Name) values('PINKALKUMAR');
insert into ref_tbGoodNamesList(Name) values('"Pradeep kumar"');
insert into ref_tbGoodNamesList(Name) values('"Prakash Kumar"');
insert into ref_tbGoodNamesList(Name) values('rakeshkumar');
insert into ref_tbGoodNamesList(Name) values('"RAVI KUMAR"');
insert into ref_tbGoodNamesList(Name) values('RINKESHKUMAR');
insert into ref_tbGoodNamesList(Name) values('Ronakkumar');
insert into ref_tbGoodNamesList(Name) values('SANTHAKUMAR');
insert into ref_tbGoodNamesList(Name) values('"Santhosh Kumar"');
insert into ref_tbGoodNamesList(Name) values('sashangkumar');
insert into ref_tbGoodNamesList(Name) values('"Satish Kumar"');
insert into ref_tbGoodNamesList(Name) values('"SHARVEN KUMAR"');
insert into ref_tbGoodNamesList(Name) values('SHYAMKUMAR');
insert into ref_tbGoodNamesList(Name) values('"Sushil Kumar"');
insert into ref_tbGoodNamesList(Name) values('Takuma');
insert into ref_tbGoodNamesList(Name) values('Thavakumar');
insert into ref_tbGoodNamesList(Name) values('THEVAKUMAR');
insert into ref_tbGoodNamesList(Name) values('Thirukumaran');
insert into ref_tbGoodNamesList(Name) values('Tushitkumar');
insert into ref_tbGoodNamesList(Name) values('VIJAYKUMAR');
insert into ref_tbGoodNamesList(Name) values('"Vikas Kumar"');
insert into ref_tbGoodNamesList(Name) values('"Vikesh Kumar"');
insert into ref_tbGoodNamesList(Name) values('"vinod kumar"');
insert into ref_tbGoodNamesList(Name) values('VINODKUMAR');
insert into ref_tbGoodNamesList(Name) values('VIPULKUMAR');
insert into ref_tbGoodNamesList(Name) values('Virenkumar');
insert into ref_tbGoodNamesList(Name) values('Lechuck');
insert into ref_tbGoodNamesList(Name) values('"Sean Mylecharane"');
insert into ref_tbGoodNamesList(Name) values('Adalene');
insert into ref_tbGoodNamesList(Name) values('"Alana Allen"');
insert into ref_tbGoodNamesList(Name) values('ALEN');
insert into ref_tbGoodNamesList(Name) values('ALENA');
insert into ref_tbGoodNamesList(Name) values('Alenka');
insert into ref_tbGoodNamesList(Name) values('ALLEN');
insert into ref_tbGoodNamesList(Name) values('"Allen Marinovich"');
insert into ref_tbGoodNamesList(Name) values('"ALLEN W"');
insert into ref_tbGoodNamesList(Name) values('"Angelene Rippingale"');
insert into ref_tbGoodNamesList(Name) values('"Anna Helena"');
insert into ref_tbGoodNamesList(Name) values('ARLENE');
insert into ref_tbGoodNamesList(Name) values('"Breallen Redman Smith"');
insert into ref_tbGoodNamesList(Name) values('BULENT');
insert into ref_tbGoodNamesList(Name) values('CAILEN');
insert into ref_tbGoodNamesList(Name) values('Callen');
insert into ref_tbGoodNamesList(Name) values('Carlene');
insert into ref_tbGoodNamesList(Name) values('CAROLEN');
insert into ref_tbGoodNamesList(Name) values('"Catherine Lennox"');
insert into ref_tbGoodNamesList(Name) values('cathlene');
insert into ref_tbGoodNamesList(Name) values('Charlene');
insert into ref_tbGoodNamesList(Name) values('Cherelene');
insert into ref_tbGoodNamesList(Name) values('Cholena');
insert into ref_tbGoodNamesList(Name) values('COLLEN');
insert into ref_tbGoodNamesList(Name) values('DAHLENE');
insert into ref_tbGoodNamesList(Name) values('Dalene');
insert into ref_tbGoodNamesList(Name) values('DARLENE');
insert into ref_tbGoodNamesList(Name) values('Delena');
insert into ref_tbGoodNamesList(Name) values('Elena');
insert into ref_tbGoodNamesList(Name) values('"Elena Patriscia"');
insert into ref_tbGoodNamesList(Name) values('ELENI');
insert into ref_tbGoodNamesList(Name) values('ELENOA');
insert into ref_tbGoodNamesList(Name) values('Elenor');
insert into ref_tbGoodNamesList(Name) values('ELENORE');
insert into ref_tbGoodNamesList(Name) values('Ellen');
insert into ref_tbGoodNamesList(Name) values('"Ellen Jones"');
insert into ref_tbGoodNamesList(Name) values('"Ellen Wilson"');
insert into ref_tbGoodNamesList(Name) values('Ellena');
insert into ref_tbGoodNamesList(Name) values('Ellene');
insert into ref_tbGoodNamesList(Name) values('"Garry Glenn"');
insert into ref_tbGoodNamesList(Name) values('Glen');
insert into ref_tbGoodNamesList(Name) values('"Glen Easton"');
insert into ref_tbGoodNamesList(Name) values('"Glen Hicks"');
insert into ref_tbGoodNamesList(Name) values('"Glen M"');
insert into ref_tbGoodNamesList(Name) values('Glenda');
insert into ref_tbGoodNamesList(Name) values('Gleness');
insert into ref_tbGoodNamesList(Name) values('GLENICE');
insert into ref_tbGoodNamesList(Name) values('Glenis');
insert into ref_tbGoodNamesList(Name) values('Glenn');
insert into ref_tbGoodNamesList(Name) values('"Glenn A"');
insert into ref_tbGoodNamesList(Name) values('"Glenn Andrew"');
insert into ref_tbGoodNamesList(Name) values('"Glenn Davies"');
insert into ref_tbGoodNamesList(Name) values('"Glenn Gemmill"');
insert into ref_tbGoodNamesList(Name) values('"Glenn Sellers"');
insert into ref_tbGoodNamesList(Name) values('"Glenn Toogood"');
insert into ref_tbGoodNamesList(Name) values('Glennis');
insert into ref_tbGoodNamesList(Name) values('Glennys');
insert into ref_tbGoodNamesList(Name) values('GLENTON');
insert into ref_tbGoodNamesList(Name) values('Glenyce');
insert into ref_tbGoodNamesList(Name) values('GLENYS');
insert into ref_tbGoodNamesList(Name) values('Glenyss');
insert into ref_tbGoodNamesList(Name) values('Helen');
insert into ref_tbGoodNamesList(Name) values('"Helen Deguet"');
insert into ref_tbGoodNamesList(Name) values('"HELEN J."');
insert into ref_tbGoodNamesList(Name) values('"Helen kun lian"');
insert into ref_tbGoodNamesList(Name) values('"Helen Majella"');
insert into ref_tbGoodNamesList(Name) values('"Helen Mary"');
insert into ref_tbGoodNamesList(Name) values('"Helen Monks-Kane"');
insert into ref_tbGoodNamesList(Name) values('Helena');
insert into ref_tbGoodNamesList(Name) values('"HELENA SOON YOU"');
insert into ref_tbGoodNamesList(Name) values('HELENE');
insert into ref_tbGoodNamesList(Name) values('"Hugh McMullen"');
insert into ref_tbGoodNamesList(Name) values('ILENE');
insert into ref_tbGoodNamesList(Name) values('Jacquelene');
insert into ref_tbGoodNamesList(Name) values('Jalen');
insert into ref_tbGoodNamesList(Name) values('Jaquilene');
insert into ref_tbGoodNamesList(Name) values('JAYLENE');
insert into ref_tbGoodNamesList(Name) values('JELENA');
insert into ref_tbGoodNamesList(Name) values('JELENKO');
insert into ref_tbGoodNamesList(Name) values('"Jerneen Helen"');
insert into ref_tbGoodNamesList(Name) values('Jocylen');
insert into ref_tbGoodNamesList(Name) values('JOELENE');
insert into ref_tbGoodNamesList(Name) values('"JOHN ALLEN"');
insert into ref_tbGoodNamesList(Name) values('jolene');
insert into ref_tbGoodNamesList(Name) values('Joylene');
insert into ref_tbGoodNamesList(Name) values('Kaelene');
insert into ref_tbGoodNamesList(Name) values('KARLEN');
insert into ref_tbGoodNamesList(Name) values('Karlena');
insert into ref_tbGoodNamesList(Name) values('kathlen');
insert into ref_tbGoodNamesList(Name) values('KAUSHLENDER');
insert into ref_tbGoodNamesList(Name) values('Kayelene');
insert into ref_tbGoodNamesList(Name) values('kaylen');
insert into ref_tbGoodNamesList(Name) values('KAYLENE');
insert into ref_tbGoodNamesList(Name) values('"Kellie Glenister"');
insert into ref_tbGoodNamesList(Name) values('KYLENE');
insert into ref_tbGoodNamesList(Name) values('Lalena');
insert into ref_tbGoodNamesList(Name) values('LAURA-ELLEN');
insert into ref_tbGoodNamesList(Name) values('LEE-ELLEN');
insert into ref_tbGoodNamesList(Name) values('LEN');
insert into ref_tbGoodNamesList(Name) values('lena');
insert into ref_tbGoodNamesList(Name) values('LENCE');
insert into ref_tbGoodNamesList(Name) values('LENELLE');
insert into ref_tbGoodNamesList(Name) values('Leng');
insert into ref_tbGoodNamesList(Name) values('LENI');
insert into ref_tbGoodNamesList(Name) values('Lenine');
insert into ref_tbGoodNamesList(Name) values('Lenka');
insert into ref_tbGoodNamesList(Name) values('Lennen');
insert into ref_tbGoodNamesList(Name) values('Lennon');
insert into ref_tbGoodNamesList(Name) values('LENNOX');
insert into ref_tbGoodNamesList(Name) values('LENNY');
insert into ref_tbGoodNamesList(Name) values('Lenore');
insert into ref_tbGoodNamesList(Name) values('LENY');
insert into ref_tbGoodNamesList(Name) values('LOU-ELLEN');
insert into ref_tbGoodNamesList(Name) values('Louellen');
insert into ref_tbGoodNamesList(Name) values('"Ma Malen"');
insert into ref_tbGoodNamesList(Name) values('MADALENA');
insert into ref_tbGoodNamesList(Name) values('Madelene');
insert into ref_tbGoodNamesList(Name) values('MADLEN');
insert into ref_tbGoodNamesList(Name) values('Magdalen');
insert into ref_tbGoodNamesList(Name) values('MAGDALENA');
insert into ref_tbGoodNamesList(Name) values('Malene');
insert into ref_tbGoodNamesList(Name) values('"MARIA FLORIELEN"');
insert into ref_tbGoodNamesList(Name) values('MARIA-ELENI');
insert into ref_tbGoodNamesList(Name) values('Marie-Helene');
insert into ref_tbGoodNamesList(Name) values('MARILENA');
insert into ref_tbGoodNamesList(Name) values('Marilene');
insert into ref_tbGoodNamesList(Name) values('Marlen');
insert into ref_tbGoodNamesList(Name) values('Marlena');
insert into ref_tbGoodNamesList(Name) values('Marlene');
insert into ref_tbGoodNamesList(Name) values('Maryellen');
insert into ref_tbGoodNamesList(Name) values('"Matthew Glenister"');
insert into ref_tbGoodNamesList(Name) values('Merlene');
insert into ref_tbGoodNamesList(Name) values('"Michael Lenzinger"');
insert into ref_tbGoodNamesList(Name) values('MILENA');
insert into ref_tbGoodNamesList(Name) values('MYLENE');
insert into ref_tbGoodNamesList(Name) values('Nalene');
insert into ref_tbGoodNamesList(Name) values('Nicolene');
insert into ref_tbGoodNamesList(Name) values('noelene');
insert into ref_tbGoodNamesList(Name) values('Noellene');
insert into ref_tbGoodNamesList(Name) values('NOLENE');
insert into ref_tbGoodNamesList(Name) values('Olena');
insert into ref_tbGoodNamesList(Name) values('Pelenatete');
insert into ref_tbGoodNamesList(Name) values('"Peter Valenti"');
insert into ref_tbGoodNamesList(Name) values('RAELENE');
insert into ref_tbGoodNamesList(Name) values('RAILENE');
insert into ref_tbGoodNamesList(Name) values('Ralene');
insert into ref_tbGoodNamesList(Name) values('"Renee Allen"');
insert into ref_tbGoodNamesList(Name) values('"Robert Allen"');
insert into ref_tbGoodNamesList(Name) values('ROD-ALLEN');
insert into ref_tbGoodNamesList(Name) values('"Rodney Glen"');
insert into ref_tbGoodNamesList(Name) values('Rolen');
insert into ref_tbGoodNamesList(Name) values('"Ronel Galen"');
insert into ref_tbGoodNamesList(Name) values('Salena');
insert into ref_tbGoodNamesList(Name) values('Salendra');
insert into ref_tbGoodNamesList(Name) values('SELENA');
insert into ref_tbGoodNamesList(Name) values('"Selena Leanore Davis"');
insert into ref_tbGoodNamesList(Name) values('SELENE');
insert into ref_tbGoodNamesList(Name) values('Shaleni');
insert into ref_tbGoodNamesList(Name) values('SHARLENE');
insert into ref_tbGoodNamesList(Name) values('Shirlene');
insert into ref_tbGoodNamesList(Name) values('SOKLENG');
insert into ref_tbGoodNamesList(Name) values('STARRLENE');
insert into ref_tbGoodNamesList(Name) values('SUELLEN');
insert into ref_tbGoodNamesList(Name) values('THIOLEN');
insert into ref_tbGoodNamesList(Name) values('"TROY ELLEN"');
insert into ref_tbGoodNamesList(Name) values('Valentin');
insert into ref_tbGoodNamesList(Name) values('"Valentin Mata"');
insert into ref_tbGoodNamesList(Name) values('VALENTINA');
insert into ref_tbGoodNamesList(Name) values('Valentine');
insert into ref_tbGoodNamesList(Name) values('Valentino');
insert into ref_tbGoodNamesList(Name) values('"VALIENT GLENN"');
insert into ref_tbGoodNamesList(Name) values('"VAN ALLEN"');
insert into ref_tbGoodNamesList(Name) values('Vasilena');
insert into ref_tbGoodNamesList(Name) values('"Zack Cerlenizza"');
insert into ref_tbGoodNamesList(Name) values('BUTHOLEZWE');
insert into ref_tbGoodNamesList(Name) values('"Jolanta Galeziewska"');
insert into ref_tbGoodNamesList(Name) values('Eloine');
insert into ref_tbGoodNamesList(Name) values('Lube');
insert into ref_tbGoodNamesList(Name) values('MAXI');
insert into ref_tbGoodNamesList(Name) values('MAXIM');
insert into ref_tbGoodNamesList(Name) values('MAXIME');
insert into ref_tbGoodNamesList(Name) values('"Maxime Johny"');
insert into ref_tbGoodNamesList(Name) values('MAXIMILIANE');
insert into ref_tbGoodNamesList(Name) values('Maximillian');
insert into ref_tbGoodNamesList(Name) values('MAXINE');
insert into ref_tbGoodNamesList(Name) values('"MAXINE AND KEN"');
insert into ref_tbGoodNamesList(Name) values('"thora maxine"');
insert into ref_tbGoodNamesList(Name) values('METHISA');
insert into ref_tbGoodNamesList(Name) values('Amutha');
insert into ref_tbGoodNamesList(Name) values('Amuthakasan');
insert into ref_tbGoodNamesList(Name) values('MUTHANNA');
insert into ref_tbGoodNamesList(Name) values('Alexanader');
insert into ref_tbGoodNamesList(Name) values('Alexnadra');
insert into ref_tbGoodNamesList(Name) values('Annadurai');
insert into ref_tbGoodNamesList(Name) values('Bernada');
insert into ref_tbGoodNamesList(Name) values('BERNADETA');
insert into ref_tbGoodNamesList(Name) values('BERNADETT');
insert into ref_tbGoodNamesList(Name) values('Bernadette');
insert into ref_tbGoodNamesList(Name) values('"Bernadette Seabert"');
insert into ref_tbGoodNamesList(Name) values('Bernadine');
insert into ref_tbGoodNamesList(Name) values('Dominador');
insert into ref_tbGoodNamesList(Name) values('"Francis Bunado"');
insert into ref_tbGoodNamesList(Name) values('Gennadiy');
insert into ref_tbGoodNamesList(Name) values('gennady');
insert into ref_tbGoodNamesList(Name) values('"Gunady Marthadiantara"');
insert into ref_tbGoodNamesList(Name) values('"JAG NADAN"');
insert into ref_tbGoodNamesList(Name) values('"JAGANNADHA RAJU"');
insert into ref_tbGoodNamesList(Name) values('junadi');
insert into ref_tbGoodNamesList(Name) values('Kanada');
insert into ref_tbGoodNamesList(Name) values('LYNADEL');
insert into ref_tbGoodNamesList(Name) values('"Muhanad abdl"');
insert into ref_tbGoodNamesList(Name) values('NADA');
insert into ref_tbGoodNamesList(Name) values('NADARRE');
insert into ref_tbGoodNamesList(Name) values('NADEEM');
insert into ref_tbGoodNamesList(Name) values('Nadeema');
insert into ref_tbGoodNamesList(Name) values('Nadeesha');
insert into ref_tbGoodNamesList(Name) values('nadeika');
insert into ref_tbGoodNamesList(Name) values('Nadene');
insert into ref_tbGoodNamesList(Name) values('NADER');
insert into ref_tbGoodNamesList(Name) values('NADEREH');
insert into ref_tbGoodNamesList(Name) values('NADHIM');
insert into ref_tbGoodNamesList(Name) values('NADHIRAH');
insert into ref_tbGoodNamesList(Name) values('NADHISHA');
insert into ref_tbGoodNamesList(Name) values('NADHUM');
insert into ref_tbGoodNamesList(Name) values('Nadia');
insert into ref_tbGoodNamesList(Name) values('Nadien');
insert into ref_tbGoodNamesList(Name) values('NADIM');
insert into ref_tbGoodNamesList(Name) values('NADINE');
insert into ref_tbGoodNamesList(Name) values('NADIR');
insert into ref_tbGoodNamesList(Name) values('"Nadira Yapa"');
insert into ref_tbGoodNamesList(Name) values('Nadiya');
insert into ref_tbGoodNamesList(Name) values('Nadja');
insert into ref_tbGoodNamesList(Name) values('NADYNE');
insert into ref_tbGoodNamesList(Name) values('NENAD');
insert into ref_tbGoodNamesList(Name) values('"NURUL NADIAH"');
insert into ref_tbGoodNamesList(Name) values('Panadee');
insert into ref_tbGoodNamesList(Name) values('"Shamiram Nadia"');
insert into ref_tbGoodNamesList(Name) values('Nazia');
insert into ref_tbGoodNamesList(Name) values('NAZIFE');
insert into ref_tbGoodNamesList(Name) values('NAZIH');
insert into ref_tbGoodNamesList(Name) values('Nazio');
insert into ref_tbGoodNamesList(Name) values('Naziya');
insert into ref_tbGoodNamesList(Name) values('"Jamie Noble"');
insert into ref_tbGoodNamesList(Name) values('Nobby');
insert into ref_tbGoodNamesList(Name) values('Nobel');
insert into ref_tbGoodNamesList(Name) values('Nobert');
insert into ref_tbGoodNamesList(Name) values('Noby');
insert into ref_tbGoodNamesList(Name) values('Sanober');
insert into ref_tbGoodNamesList(Name) values('CORAL');
insert into ref_tbGoodNamesList(Name) values('CORALIE');
insert into ref_tbGoodNamesList(Name) values('"Coralie Stringer"');
insert into ref_tbGoodNamesList(Name) values('Coralleen');
insert into ref_tbGoodNamesList(Name) values('Jorgan');
insert into ref_tbGoodNamesList(Name) values('"Michael Morgan"');
insert into ref_tbGoodNamesList(Name) values('MORGAN');
insert into ref_tbGoodNamesList(Name) values('MORGAN-LEA');
insert into ref_tbGoodNamesList(Name) values('Morgana');
insert into ref_tbGoodNamesList(Name) values('"Peter Morgan"');
insert into ref_tbGoodNamesList(Name) values('"Tumaaro Morgan"');
insert into ref_tbGoodNamesList(Name) values('"Peerapot Phiyasirikul"');
insert into ref_tbGoodNamesList(Name) values('"Pimprapa Kerdmanee"');
insert into ref_tbGoodNamesList(Name) values('Poonam');
insert into ref_tbGoodNamesList(Name) values('ANITAPORN');
insert into ref_tbGoodNamesList(Name) values('Jiraporn');
insert into ref_tbGoodNamesList(Name) values('Naphaporn');
insert into ref_tbGoodNamesList(Name) values('Nipaporn');
insert into ref_tbGoodNamesList(Name) values('Pornphet');
insert into ref_tbGoodNamesList(Name) values('"Siriporn Verbuyst"');
insert into ref_tbGoodNamesList(Name) values('"Suttaporn Battershill"');
insert into ref_tbGoodNamesList(Name) values('Tosaporn');
insert into ref_tbGoodNamesList(Name) values('WACHIRAPORN');
insert into ref_tbGoodNamesList(Name) values('"Amarpreet Kaur Madanpotra"');
insert into ref_tbGoodNamesList(Name) values('"John Potts"');
insert into ref_tbGoodNamesList(Name) values('PRUDENCE');
insert into ref_tbGoodNamesList(Name) values('Joaquim');
insert into ref_tbGoodNamesList(Name) values('Tracy');
insert into ref_tbGoodNamesList(Name) values('"Tracy Ellingham"');
insert into ref_tbGoodNamesList(Name) values('"Tracy Gibson"');
insert into ref_tbGoodNamesList(Name) values('"Tracy Huynh"');
insert into ref_tbGoodNamesList(Name) values('"Tracy Riddle"');
insert into ref_tbGoodNamesList(Name) values('"Tracy Toomey"');
insert into ref_tbGoodNamesList(Name) values('TRACY-ANN');
insert into ref_tbGoodNamesList(Name) values('TRACY-LEE');
insert into ref_tbGoodNamesList(Name) values('tracye');
insert into ref_tbGoodNamesList(Name) values('Arum');
insert into ref_tbGoodNamesList(Name) values('Arumugam');
insert into ref_tbGoodNamesList(Name) values('"Patrick Kenneth Meldrum"');
insert into ref_tbGoodNamesList(Name) values('RUMBIDZAI');
insert into ref_tbGoodNamesList(Name) values('"Rumbidzai O"');
insert into ref_tbGoodNamesList(Name) values('Tharumini');
insert into ref_tbGoodNamesList(Name) values('THIRUMAGAL');
insert into ref_tbGoodNamesList(Name) values('Bhashita');
insert into ref_tbGoodNamesList(Name) values('Nishit');
insert into ref_tbGoodNamesList(Name) values('Preshit');
insert into ref_tbGoodNamesList(Name) values('YOSHITAKE');
insert into ref_tbGoodNamesList(Name) values('SLAVE');
insert into ref_tbGoodNamesList(Name) values('ChrisChristien');
insert into ref_tbGoodNamesList(Name) values('christard');
insert into ref_tbGoodNamesList(Name) values('CTMTestE');
insert into ref_tbGoodNamesList(Name) values('Mathugh');
insert into ref_tbGoodNamesList(Name) values('"Adrian Titulaer"');
insert into ref_tbGoodNamesList(Name) values('"Colin Pettit"');
insert into ref_tbGoodNamesList(Name) values('Laetitia');
insert into ref_tbGoodNamesList(Name) values('LETITIA');
insert into ref_tbGoodNamesList(Name) values('Titia');
insert into ref_tbGoodNamesList(Name) values('Tito');
insert into ref_tbGoodNamesList(Name) values('TITUS');
insert into ref_tbGoodNamesList(Name) values('"Joel Stokes"');
insert into ref_tbGoodNamesList(Name) values('Tushar');
insert into ref_tbGoodNamesList(Name) values('Lourinete');
insert into ref_tbGoodNamesList(Name) values('"Amanda  Ruzicska"');
insert into ref_tbGoodNamesList(Name) values('"Daniel Ruzicska"');
insert into ref_tbGoodNamesList(Name) values('FAUZIA');
insert into ref_tbGoodNamesList(Name) values('Fuzi');
insert into ref_tbGoodNamesList(Name) values('SUZI');
insert into ref_tbGoodNamesList(Name) values('Suzie');
insert into ref_tbGoodNamesList(Name) values('EVAGELIA');
insert into ref_tbGoodNamesList(Name) values('"Gordon Derritt Salvage"');
insert into ref_tbGoodNamesList(Name) values('"Petra Joy Salvage"');
insert into ref_tbGoodNamesList(Name) values('Sivagnanasundaram');
insert into ref_tbGoodNamesList(Name) values('VIRGINIA');
insert into ref_tbGoodNamesList(Name) values('"VIRGINIA YICK H"');
insert into ref_tbGoodNamesList(Name) values('Hawada');
insert into ref_tbGoodNamesList(Name) values('Jawad');
insert into ref_tbGoodNamesList(Name) values('"Malish Palihawadana"');
insert into ref_tbGoodNamesList(Name) values('WADAN');
insert into ref_tbGoodNamesList(Name) values('WADE');
insert into ref_tbGoodNamesList(Name) values('"Wade Pavey"');
insert into ref_tbGoodNamesList(Name) values('"Wade Starr"');
insert into ref_tbGoodNamesList(Name) values('WADIE');
insert into ref_tbGoodNamesList(Name) values('"HWANG MIN"');
insert into ref_tbGoodNamesList(Name) values('Jiawang');
insert into ref_tbGoodNamesList(Name) values('Kwang');
insert into ref_tbGoodNamesList(Name) values('"Kwang Kee"');
insert into ref_tbGoodNamesList(Name) values('"Lamei Wang"');
insert into ref_tbGoodNamesList(Name) values('"YOUNG KWANG"');
insert into ref_tbGoodNamesList(Name) values('"Michael Willys"');
insert into ref_tbGoodNamesList(Name) values('Willy');
insert into ref_tbGoodNamesList(Name) values('WOODY');




